### ISSUE TITLE
Bug: Latest from today 6/5/22 won't get forward port for PIA

### ISSUE THREAD

**Issue by dsm1212** [qdm12/gluetun#1014]
### Is this urgent?

No

### Host OS

Docker on debian buster

### CPU arch

x86_64

### VPN service provider

Private Internet Access

### What are you using to run the container

Portainer

### What is the version of Gluetun

Running version latest built on 2022-06-05T16:05:56.477Z (commit f5f65d5)

### What's the problem 🤔

I just pulled latest and it get a log full of these messages below. I reverted to v3 image and is fine. I have REGION set to CA Montreal. I thought maybe PIA dropped port forwarding from ca montreal but reverting worked so it must be a bug in the gluetun image.

### Share your logs

```log
2022-06-05T21:31:19-04:00 ERROR [port forwarding] server name not found in servers: ca-montreal.privacy.network
2022-06-05T21:31:19-04:00 INFO [port forwarding] retrying in 5s
2022-06-05T21:31:24-04:00 ERROR [port forwarding] server name not found in servers: ca-montreal.privacy.network
2022-06-05T21:31:24-04:00 INFO [port forwarding] retrying in 5s
2022-06-05T21:31:29-04:00 ERROR [port forwarding] server name not found in servers: ca-montreal.privacy.network
2022-06-05T21:31:29-04:00 INFO [port forwarding] retrying in 5s
2022-06-05T21:31:34-04:00 ERROR [port forwarding] server name not found in servers: ca-montreal.privacy.network
2022-06-05T21:31:34-04:00 INFO [port forwarding] retrying in 5s
2022-06-05T21:31:39-04:00 ERROR [port forwarding] server name not found in servers: ca-montreal.privacy.network
2022-06-05T21:31:39-04:00 INFO [port forwarding] retrying in 5s
2022-06-05T21:31:44-04:00 ERROR [port forwarding] server name not found in servers: ca-montreal.privacy.network
```

### Share your configuration

```yml
gluetun:
    image: qmcgaw/gluetun:v3
    container_name: gluetun
    network_mode: lsio
    cap_add:
      - NET_ADMIN
    ports:
      - 8001:8000 # gluetun control
      - 8191:8191 # flaresolvrr
      - 9092:8080 # calibre
      - 9093:8086 # calibre api
    volumes:
      - /apps/gluetun:/gluetun
      - /apps/gluetun/post-rules.txt:/iptables/post-rules.txt
    environment:
      - DOT_IPV6=on
      - VPNSP=private internet access
      - OPENVPN_USER=redacted
      - OPENVPN_PASSWORD=redacted
      - OPENVPN_FLAGS=--fast-io --txqueuelen 2000
      - REGION=CA Montreal
      - PORT_FORWARDING=on
      - PORT_FORWARDING_STATUS_FILE=/gluetun/forwarded_port
      - TZ=America/New_York
    restart: unless-stopped
```

So I realized after I submitted this that the log was all there, portainer just truncated it to 100 lines. So I restarted with latest to get the version and more log. This time I only got the message once. I don't think I got a port number though. So I'm switching back to v3 again. Here is the tail of the log from 2nd try that didn't seem to get the port: 

```
2022-06-05T21:47:31-04:00 INFO [openvpn] TUN/TAP device tun0 opened
2022-06-05T21:47:31-04:00 INFO [openvpn] /sbin/ip link set dev tun0 up mtu 1500
2022-06-05T21:47:31-04:00 INFO [openvpn] /sbin/ip link set dev tun0 up
2022-06-05T21:47:31-04:00 INFO [openvpn] /sbin/ip addr add dev tun0 10.37.110.20/24
2022-06-05T21:47:31-04:00 INFO [openvpn] UID set to nonrootuser
2022-06-05T21:47:31-04:00 INFO [openvpn] Initialization Sequence Completed
2022-06-05T21:47:31-04:00 INFO [dns over tls] downloading DNS over TLS cryptographic files
2022-06-05T21:47:31-04:00 INFO [dns over tls] downloading hostnames and IP block lists
2022-06-05T21:47:32-04:00 INFO [healthcheck] healthy!
2022-06-05T21:47:35-04:00 INFO [dns over tls] init module 0: validator
2022-06-05T21:47:35-04:00 INFO [dns over tls] init module 1: iterator
2022-06-05T21:47:35-04:00 INFO [dns over tls] start of service (unbound 1.15.0).
2022-06-05T21:47:35-04:00 INFO [dns over tls] generate keytag query _ta-4a5c-4f66. NULL IN
2022-06-05T21:47:38-04:00 INFO [dns over tls] ready
2022-06-05T21:47:38-04:00 INFO [vpn] You are running on the bleeding edge of latest!
2022-06-05T21:47:38-04:00 INFO [vpn] VPN gateway IP address: 10.37.110.1
2022-06-05T21:47:38-04:00 ERROR [port forwarding] server name not found in servers: ca-montreal.privacy.network
2022-06-05T21:47:38-04:00 INFO [port forwarding] retrying in 5s
2022-06-05T21:47:39-04:00 INFO [ip getter] Public IP address is 172.98.71.103 (Canada, Quebec, Montréal)
2022-06-05T21:47:40-04:00 INFO [healthcheck] unhealthy: cannot dial: dial tcp4: i/o timeout
2022-06-05T21:47:41-04:00 INFO [healthcheck] healthy!
```

I think the updated servers.json for CA Montreal region must be wrong or something. The servers completely changed names, but the ones in v3 work.

**Comment by dsm1212** [comment]
So I realized after I submitted this that the log was all there, portainer just truncated it to 100 lines. So I restarted with latest to get the version and more log. This time I only got the message once. I don't think I got a port number though. So I'm switching back to v3 again. Here is the tail of the log from 2nd try that didn't seem to get the port: 

2022-06-05T21:47:31-04:00 INFO [openvpn] TUN/TAP device tun0 opened
2022-06-05T21:47:31-04:00 INFO [openvpn] /sbin/ip link set dev tun0 up mtu 1500
2022-06-05T21:47:31-04:00 INFO [openvpn] /sbin/ip link set dev tun0 up
2022-06-05T21:47:31-04:00 INFO [openvpn] /sbin/ip addr add dev tun0 10.37.110.20/24
2022-06-05T21:47:31-04:00 INFO [openvpn] UID set to nonrootuser
2022-06-05T21:47:31-04:00 INFO [openvpn] Initialization Sequence Completed
2022-06-05T21:47:31-04:00 INFO [dns over tls] downloading DNS over TLS cryptographic files
2022-06-05T21:47:31-04:00 INFO [dns over tls] downloading hostnames and IP block lists
2022-06-05T21:47:32-04:00 INFO [healthcheck] healthy!
2022-06-05T21:47:35-04:00 INFO [dns over tls] init module 0: validator
2022-06-05T21:47:35-04:00 INFO [dns over tls] init module 1: iterator
2022-06-05T21:47:35-04:00 INFO [dns over tls] start of service (unbound 1.15.0).
2022-06-05T21:47:35-04:00 INFO [dns over tls] generate keytag query _ta-4a5c-4f66. NULL IN
2022-06-05T21:47:38-04:00 INFO [dns over tls] ready
2022-06-05T21:47:38-04:00 INFO [vpn] You are running on the bleeding edge of latest!
2022-06-05T21:47:38-04:00 INFO [vpn] VPN gateway IP address: 10.37.110.1
2022-06-05T21:47:38-04:00 ERROR [port forwarding] server name not found in servers: ca-montreal.privacy.network
2022-06-05T21:47:38-04:00 INFO [port forwarding] retrying in 5s
2022-06-05T21:47:39-04:00 INFO [ip getter] Public IP address is 172.98.71.103 (Canada, Quebec, Montréal)
2022-06-05T21:47:40-04:00 INFO [healthcheck] unhealthy: cannot dial: dial tcp4: i/o timeout
2022-06-05T21:47:41-04:00 INFO [healthcheck] healthy!

**Comment by dsm1212** [comment]
I think the updated servers.json for CA Montreal region must be wrong or something. The servers completely changed names, but the ones in v3 work.

**Comment by qdm12** [comment]
I changed some finding of a server using a server name today, although I can't see how it affects the problem you got.

Can you please run image `qmcgaw/gluetun:1014` (built for amd64 only) and run it with `LOG_LEVEL=debug`? It should log

```
Checking for server name xxx
Against server name yyy
...
Against server name zzz
```

Please share that part of the log to help me understand what's wrong :wink: Thanks!

**Comment by twistedsanity** [comment]
Not sure if there is anything I can add other than I have the same issue with the Switzerland region selected.

**Comment by twistedsanity** [comment]
`2022-06-06T09:55:16+01:00 DEBUG [storage] Checking for server name swiss.privacy.network
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name melbourne414
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name melbourne426
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name melbourne427
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name melbourne429
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name perth403
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name perth404
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name perth405
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name sydney420
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name sydney424
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name sydney430
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name sydney434
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name sydney436
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name tirana401
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name tirana402
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name algiers403
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name algiers404
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name andorra403
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name andorra404
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name andorra405
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name buenosaires405
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name buenosaires406
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name buenosaires407
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name armenia403
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name vienna401
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name vienna402
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name bahamas404
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name bahamas405
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name bahamas406
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name bahamas409
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name bangladesh403
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name brussels408
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name brussels418
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name brussels420
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name sarajevo402
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name saopaolo401
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name saopaolo403
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name saopaolo404
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name saopaolo405
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name montreal402
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name montreal406
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name montreal410
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name ontario405
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name ontario411
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name toronto402
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name toronto418
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name toronto423
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name vancouver401
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name vancouver405
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name vancouver408
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name vancouver409
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name cambodia401
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name chile401
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name china404
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name china406
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name colombia402
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name costarica401
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name zagreb402
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name cyprus403
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name prague401
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name prague403
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name berlin418
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name berlin419
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name berlin421
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name frankfurt405
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name frankfurt406
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name frankfurt407
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name frankfurt410
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name copenhagen402
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name copenhagen403
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name copenhagen404
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name copenhagen405
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name madrid401
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name madrid403
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name valencia401
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name cairo402
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name talinn402
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name talinn403
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name helsinki402
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name helsinki403
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name helsinki404
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name helsinki401
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name paris402
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name paris404
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name paris410
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name georgia403
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name athens402
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name greenland405
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name greenland406
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name greenland407
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name hongkong403
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name hongkong404
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name hongkong405
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name budapest401
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name budapest402
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name budapest405
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name milano402
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name milano404
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name milano405
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name milano406
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name reykjavik402
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name mumbai414
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name indonesia401
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name dublin403
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name dublin406
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name dublin407
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name dublin411
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name douglas403
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name jerusalem412
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name jerusalem413
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name tokyo410
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name tokyo403
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name tokyo405
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name kazakhstan403
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name riga406
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name liechtenstein401
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name liechtenstein403
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name vilnius401
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name luxembourg404
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name luxembourg407
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name macau403
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name malaysia402
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name malta403
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name malta405
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name mexico405
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name mexico406
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name mexico407
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name mexico410
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name chisinau402
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name monaco403
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name mongolia403
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name mongolia404
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name montenegro403
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name morocco403
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name amsterdam412
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name amsterdam433
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name newzealand404
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name nigeria405
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name nigeria406
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name oslo401
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name oslo402
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name oslo403
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name panama404
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name panama405
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name panama407
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name panama408
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name philippines401
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name philippines402
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name warsaw410
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name lisbon405
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name qatar403
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name qatar404
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name romania406
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name romania407
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name stockholm402
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name stockholm406
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name stockholm407
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name saudiarabia403
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name saudiarabia404
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name belgrade402
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name singapore402
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name singapore404
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name bratislava402
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name bratislava403
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name slovenia401
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name johannesburg407
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name johannesburg408
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name srilanka403
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name zurich406
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name zurich407
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name taiwan402
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name taiwan403
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name taiwan404
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name istanbul402
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name london405
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name london407
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name london413
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name manchester419
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name manchester425
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name southampton401
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name southampton403
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name southampton406
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name london435
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name london441
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name london445
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name atlanta419
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name atlanta421
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name atlanta422
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name baltimore401
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name baltimore402
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name losangeles433
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name losangeles434
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name chicago401
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name chicago410
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name chicago429
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name denver402
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name denver404
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name newjersey432
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name newjersey436
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name newjersey440
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name newjersey419
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name miami404
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name miami417
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name honolulu401
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name houston421
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name houston423
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name lasvegas426
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name lasvegas428
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name newyork438
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name newyork440
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name saltlake402
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name seattle401
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name seattle415
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name seattle418
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name siliconvalley402
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name siliconvalley404
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name siliconvalley414
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name siliconvalley418
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name siliconvalley420
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name dallas407
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name dallas408
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name dallas416
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name washington435
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name washington437
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name washington439
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name washington441
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name washington442
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name washington452
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name phoenix407
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name phoenix408
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name phoenix409
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name phoenix410
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name siliconvalley410
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name wilmington401
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name wilmington402
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name kiev407
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name dubai403
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name dubai404
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name venezuela405
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name venezuela406
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name vietnam401
2022-06-06T09:55:16+01:00 DEBUG [storage] Against server name vietnam402
2022-06-06T09:55:16+01:00 ERROR [port forwarding] server name not found in servers: swiss.privacy.network

2022-06-06T09:55:16+01:00 INFO [port forwarding] retrying in 5s
2022-06-06T09:55:16+01:00 INFO [ip getter] Public IP address is 156.146.62.197 (Switzerland, Zurich, Zürich)
2022-06-06T09:55:21+01:00 DEBUG [storage] Checking for server name swiss.privacy.network`

**Comment by ispiropoulos** [comment]
Getting the same problem as well. Tried with Austria and France.

**Comment by dsm1212** [comment]
It's suspicious to me that the code is looking up by a field called "server name", but the string printed out is the hostname. Unless the naming in the code is off, I think maybe somewhere in a recent checkin hostname got passed instead of server name?

**Comment by twistedsanity** [comment]
Both v3.29.0 and v3.28.2 work with port forwarding for me.

**Comment by qdm12** [comment]
Awesome :+1: 

`:latest` should now be fixed with 5359257c65be20fc050154abbe54fdf51fc423eb I'll close the issue, but feel free to let me know the outcome! Again thanks for using the latest image to debunk these bugs! :medal_military:

**Comment by dsm1212** [comment]
Hate to tell you this but I get a different error :-). Submit new bug?

2022-06-06T14:30:51-04:00 INFO [port forwarding] Port forwarded data expires in 5 days
2022-06-06T14:30:51-04:00 ERROR [port forwarding] cannot bind port: Get "https://10.45.110.1:19999/bindPort?payload=<payload>&signature=<signature>": x509: certificate signed by unknown authority
2022-06-06T14:30:51-04:00 INFO [port forwarding] retrying in 5s
2022-06-06T14:30:51-04:00 INFO [ip getter] Public IP address is 172.98.71.111 (Canada, Quebec, Montréal)
2022-06-06T14:30:56-04:00 INFO [port forwarding] Found saved forwarded port data for port 27671
2022-06-06T14:30:56-04:00 INFO [port forwarding] Forwarded port data expires in 5 days
2022-06-06T14:30:56-04:00 INFO [port forwarding] Port forwarded data expires in 5 days
2022-06-06T14:30:56-04:00 ERROR [port forwarding] cannot bind port: Get "https://10.45.110.1:19999/bindPort?payload=<payload>&signature=<signature>": x509: certificate signed by unknown authority
2022-06-06T14:30:56-04:00 INFO [port forwarding] retrying in 5s
2022-06-06T14:31:01-04:00 INFO [port forwarding] Found saved forwarded port data for port 27671
2022-06-06T14:31:01-04:00 INFO [port forwarding] Forwarded port data expires in 5 days
2022-06-06T14:31:01-04:00 INFO [port forwarding] Port forwarded data expires in 5 days
2022-06-06T14:31:01-04:00 ERROR [port forwarding] cannot bind port: Get "https://10.45.110.1:19999/bindPort?payload=<payload>&signature=<signature>": x509: certificate signed by unknown authority
2022-06-06T14:31:01-04:00 INFO [port forwarding] retrying in 5s
2022-06-06T14:31:06-04:00 INFO [port forwarding] Found saved forwarded port data for port 27671
2022-06-06T14:31:06-04:00 INFO [port forwarding] Forwarded port data expires in 5 days
2022-06-06T14:31:06-04:00 INFO [port forwarding] Port forwarded data expires in 5 days
2022-06-06T14:31:06-04:00 ERROR [port forwarding] cannot bind port: Get "https://10.45.110.1:19999/bindPort?payload=<payload>&signature=<signature>": x509: certificate signed by unknown authority

**Comment by qdm12** [comment]
@dsm1212 and if you remove the port forwarding data from the gluetun directory, does it work with v3.29.0?

It might be related to https://github.com/qdm12/gluetun/issues/958 which got fixed by commit https://github.com/qdm12/gluetun/commit/db91625de45c90935de1bac3897b3dfcfcccad19 🤔 Maybe we need to revert it or something, although if it works with v3.29.0, then it's likely another problem.

**Comment by dsm1212** [comment]
3.29.0 always works for me. I switched back to that and is fine. I can try removing the port forward json file and use latest again. Not sure if that's what you meant, but it only takes a minute. Stand by

**Comment by dsm1212** [comment]
Nope removing the json file didn't change it:

2022-06-06T16:54:09-04:00 ERROR [port forwarding] cannot refresh port forward data: cannot fetch port forwarding data: cannot obtain signature payload: Get "https://10.42.110.1:19999/getSignature?token=<token>": x509: certificate signed by unknown authority
2022-06-06T16:54:09-04:00 INFO [port forwarding] retrying in 5s
2022-06-06T16:54:14-04:00 ERROR [port forwarding] cannot refresh port forward data: cannot fetch port forwarding data: cannot obtain signature payload: Get "https://10.42.110.1:19999/getSignature?token=<token>": x509: certificate signed by unknown authority
2022-06-06T16:54:14-04:00 INFO [port forwarding] retrying in 5s
2022-06-06T16:54:19-04:00 ERROR [port forwarding] cannot refresh port forward data: cannot fetch port forwarding data: cannot obtain signature payload: Get "https://10.42.110.1:19999/getSignature?token=<token>": x509: certificate signed by unknown authority
2022-06-06T16:54:19-04:00 INFO [port forwarding] retrying in 5s
2022-06-06T16:54:24-04:00 ERROR [port forwarding] cannot refresh port forward data: cannot fetch port forwarding data: cannot obtain signature payload: Get "https://10.42.110.1:19999/getSignature?token=<token>": x509: certificate signed by unknown authority
2022-06-06T16:54:24-04:00 INFO [port forwarding] retrying in 5s

**Comment by dsm1212** [comment]
Is it possible the new container is missing some certificates? If a server doesn't respond with the whole cert chain and the client doesn't have the base cert then it will report this I think.

**Comment by qdm12** [comment]
Try removing the json port forwarding data then run v3.29 and see if it works?

If it does work try building gluetun with alpine 3.15:

```
docker build -t qmcgaw/gluetun:alpine3.15 --build-arg ALPINE_VERSION=3.15 https://github.com/qdm12/gluetun.git
```

And then use image `qmcgaw/gluetun:alpine3.15`

I'm suspecting Alpine 3.16 comes with CA certificates that are newer and the PIA ones got revoked. Maybe I'm terribly wrong though, but it's worth a try!

**Comment by principis** [comment]
Building with Alpine 3.15 doesn't solve it for me

**Comment by principis** [comment]
Just checked, they sign their own certificates for the ip addresses for example: https://156.146.62.134:19999/
But when using the domain name https://https://swiss.privacy.network:19999 it works fine.

**Comment by dsm1212** [comment]
@qdm12 I suspect in the old code you used the hostname to do the bindport and now you are using the IP. When I'm in the new container I can wget ca-montreal.privacy.network but if I use the IP I get a certificate error.

**Comment by hmorrico** [comment]
This is the error I am getting with latest.

ERROR [port forwarding] cannot refresh port forward data: cannot fetch port forwarding data: cannot obtain signature payload: Get "https://x.x.x.x:19999/getSignature?token=<token>": x509: certificate signed by unknown authority

by only adding this tag to my compose
- PRIVATE_INTERNET_ACCESS_VPN_PORT_FORWARDING=on

if I remove the tag it connects fine with no error, obviously no port forwarding either.

**Comment by qdm12** [comment]
I pushed 7f32b4389512c85b86b82ea6227193a4bb3065ff that may fix it for the latest image, let me know (test with `docker pull qmcgaw/gluetun` then restart gluetun).
It should now load the custom PIA certificate on top of the system certificates.

**Comment by qdm12** [comment]
Awesome! Closing this for now, feel free to let me know if it still doesn't work.

**Comment by hmorrico** [comment]
Still doesnt work for me on latest tag, not sure if that is different to what you said. it seems to get a port now but cant bind it

2022-06-10T08:44:14Z INFO [port forwarding] Found saved forwarded port data for port 33808
2022-06-10T08:44:14Z INFO [port forwarding] Forwarded port data expires in 61 days
2022-06-10T08:44:14Z INFO [port forwarding] Port forwarded data expires in 61 days
2022-06-10T08:44:14Z ERROR [port forwarding] cannot bind port: Get "https://x.x.x.x:19999/bindPort?payload=<payload>&signature=<signature>": x509: certificate signed by unknown authority
2022-06-10T08:44:14Z INFO [port forwarding] retrying in 5s

**Comment by twistedsanity** [comment]
looks to be work perfectly for me running ebd9472 thank you so much qdm12!

**Comment by dsm1212** [comment]
> Still doesnt work for me on latest tag, not sure if that is different to what you said. it seems to get a port now but cant bind it

This looks like the issue addressed in the final fix. Make sure you have pulled the latest image. Stop the container, pull the latest one, delete the old image so you know it is gone and then restart. If you are using portainer you just stop the container, delete the image and restart.

**Comment by qdm12** [comment]
@hmorrico if it still doesn't work, please report what gluetun version you are running at the top of your logs.

On a side note, I am still confused at to why it works on v3.29.0 (v3) and stopped working on `:latest` 😕

**Comment by dsm1212** [comment]
Great! @qdm12 are your sure that the host name was not being used in 3.29.0? Host name worked because it pulls and https cert from their web service that is different. When you hit the IP address it’s coming back with the cert they use for openvpn tls connecting.

**Comment by qdm12** [comment]
@dsm1212 you are totally right, my bad! It was using the **hostname** instead of the **server name** in v3.29.0. My code was quite confusing since I was using `serverName` as a variable name instead of `hostname`. I probably used server name instead of hostname when refactoring due to that bad naming carried over from v3.29.0.

Now...

The latest image currently (TLS) validates the (LAN) server name using the custom PIA certificate. It cannot be validated by system certificates since it's not a "public" hostname.

Now, the PIA hostnames (i.e. `blabla.privacy`) are signed by public CAs, hence we did not need the custom PIA certificate in v3.29.0.

I'm now wondering which one is better, to validate with the custom PIA certificate or to use the system certificates to validate the hostname. Anyone has opinion on this? 🤔 I guess it works as is, and we then only rely on PIA; if some OS certificates get revoked in the future it won't affect us.

**Comment by dsm1212** [comment]
Either seems ok to me and as you say since this certificate is widely distributed among customers it is unlikely to change or stop working. If they did switch to the web cert it would work too so this way you are covered :-).

**Comment by dsm1212** [comment]
BTW Thanks!
