### ISSUE TITLE
Bug: Container exits on startup (commit ac5141b)

### ISSUE THREAD

**Issue by oester** [qdm12/gluetun#1421]
### Is this urgent?

Yes

### Host OS

Ubuntu 22.04

### CPU arch

x86_64

### VPN service provider

Mullvad

### What are you using to run the container

docker run

### What is the version of Gluetun

Running version latest built on 2023-02-26T19:18:36.074Z (commit ac5141b)

### What's the problem 🤔

Container exits on startup. Reverting back to v3 works successfully.

### Share your logs

```plain text
========================================
========================================
=============== gluetun ================
========================================
=========== Made with ❤️ by ============
======= https://github.com/qdm12 =======
========================================
========================================

Running version latest built on 2023-02-26T19:18:36.074Z (commit ac5141b)

🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
🐛 Bug? https://github.com/qdm12/gluetun/issues/new
✨ New feature? https://github.com/qdm12/gluetun/issues/new
☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
💻 Email? quentin.mcgaw@gmail.com
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2023-02-26T20:19:54Z INFO [routing] default route found: interface eth0, gateway 172.18.0.1 and assigned IP 172.18.0.3
2023-02-26T20:19:54Z INFO [routing] local ethernet link found: eth0
2023-02-26T20:19:54Z INFO [routing] local ipnet found: 172.18.0.0/16
2023-02-26T20:19:54Z INFO [firewall] enabling...
2023-02-26T20:19:54Z INFO [firewall] enabled successfully
2023-02-26T20:19:55Z INFO [storage] merging by most recent 13163 hardcoded servers and 13163 servers read from /gluetun/servers.json
2023-02-26T20:19:55Z INFO Alpine version: 3.17.2
2023-02-26T20:19:55Z ERROR exit status 127
2023-02-26T20:19:55Z INFO Shutdown successful
```

### Share your configuration

```yml
image: qmcgaw/gluetun:latest
    volumes:
      - /home/oester/docker/gluetun:/gluetun
    ports:
      - 8888:8888/tcp
      - 8081:8081/tcp
      - 5800:5800/tcp
      - 7878:7878/tcp
      - 9117:9117/tcp
      - 9089:8989/tcp
      - 6789:6789/tcp
      - 6767:6767/tcp
      - 8083:8080/tcp
      - 8009:8000/tcp
      - 9696:9696/tcp
      - 3000:3000/tcp
    environment:

      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=XXXX
      - WIREGUARD_ADDRESSES=10.67.227.216/32
      - SERVER_CITIES=Toronto

    cap_add:
      - NET_ADMIN
```

**Comment by stenehall** [comment]
Same problem. Going back to v3.32.0 and it's back up tho.

**Comment by phybersplice** [comment]
Yep - I got the same result - Error 127 - same scenario since the recent update.
I also emailed Quentin about this.

**Comment by EthanC** [comment]
+1 

```
========================================
========================================
=============== gluetun ================
========================================
=========== Made with ❤️ by ============
======= https://github.com/qdm12 =======
========================================
========================================
Running version latest built on 2023-02-26T19:18:36.074Z (commit ac5141b)
🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
🐛 Bug? https://github.com/qdm12/gluetun/issues/new
✨ New feature? https://github.com/qdm12/gluetun/issues/new
☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
💻 Email? quentin.mcgaw@gmail.com
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2023-02-26T15:23:52-06:00 INFO [routing] default route found: interface eth0, gateway 172.24.0.1 and assigned IP 172.24.0.4
2023-02-26T15:23:52-06:00 INFO [routing] local ethernet link found: eth0
2023-02-26T15:23:52-06:00 INFO [routing] local ipnet found: 172.24.0.0/16
2023-02-26T15:23:52-06:00 INFO [firewall] enabling...
2023-02-26T15:23:52-06:00 INFO [firewall] enabled successfully
2023-02-26T15:23:52-06:00 INFO [storage] merging by most recent 13163 hardcoded servers and 13163 servers read from /gluetun/servers.json
2023-02-26T15:23:52-06:00 INFO Alpine version: 3.17.2
2023-02-26T15:23:52-06:00 ERROR exit status 127
2023-02-26T15:23:52-06:00 INFO Shutdown successful
```

**Comment by ansred** [comment]
Same here.

Docker host DSM Synology

```
Running version latest built on 2023-02-26T19:18:36.074Z (commit ac5141b)
🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
🐛 Bug? https://github.com/qdm12/gluetun/issues/new
✨ New feature? https://github.com/qdm12/gluetun/issues/new
☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
💻 Email? quentin.mcgaw@gmail.com
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2023-02-26T17:45:38-05:00 INFO [routing] default route found: interface eth0, gateway 172.21.0.1 and assigned IP 172.21.0.2
2023-02-26T17:45:38-05:00 INFO [routing] local ethernet link found: eth0
2023-02-26T17:45:38-05:00 INFO [routing] local ipnet found: 172.21.0.0/16
2023-02-26T17:45:38-05:00 INFO [firewall] enabling...
2023-02-26T17:45:39-05:00 INFO [firewall] enabled successfully
2023-02-26T17:45:39-05:00 INFO [storage] merging by most recent 13163 hardcoded servers and 13163 servers read from /gluetun/servers.json
2023-02-26T17:45:39-05:00 INFO Alpine version: 3.17.2
2023-02-26T17:45:39-05:00 ERROR exit status 127
2023-02-26T17:45:39-05:00 INFO Shutdown successful
```

**Comment by Mindstorm1750** [comment]
Rpi4, Debian same issue, rolled back to previous version.

**Comment by procheeseburger** [comment]
same.. happy to see its not just me

**Comment by FrancisCaille** [comment]
Same here, Thanks @ansred

**Comment by cyberman6877** [comment]
Having the same issue, had to revier back to version 3.32.0 to get it to work again.  Today's update definitely broke it

**Comment by qdm12** [comment]
Fixed in e955adc1e1fca5701835ced3ec45620b05aab392 my bad, just jumped back into development yesterday after 2 months offline, what a mess 😆

I'll add a CI step to actually run Gluetun fully for a minute, to prevent this from happening again.

**Comment by procheeseburger** [comment]
@qdm12  thanks!!

**Comment by nova77** [comment]
OMG, I was going crazy with my new setup! :)
Btw, I still get the same issue even on `qmcgaw/gluetun:latest`, while `qmcgaw/gluetun:v3.32.0` works fine.

**Comment by qdm12** [comment]
@nova77 are you sure you repulled the image? I don't have the issue on my side.

**Comment by cyberman6877** [comment]
@nova77 You may need to delete the old images, do the following:

docker image ls
once you have identified the old container, delete it with docker rm -f command

then try and repull a new image, it should work!

**Comment by nova77** [comment]
> @nova77 are you sure you repulled the image? I don't have the issue on my side.

Yeah, see my "edit". I'm still rather new with docker, but I thought it would automatically figure a new version is available (hash?).
