### ISSUE TITLE
Feature request: PIA Port Forwarding Wireguard Custom Config

### ISSUE THREAD

**Issue by xtinct101** [qdm12/gluetun#2320]
### What's the feature 🧐

Hello,

Firstly, thanks for your continued work on Gluetun.
I use PIA and switched to a custom wireguard config from openvpn. Everything works great except that when I try to use the "VPN_PORT_FORWARDING=on" with custom provider I get an error stating that it can only be used with PIA service provider.
I'd like to have the PIA port fowarding when using wireguard but I've searched the wiki and issues section but could find a solution for this.
Any help would be appreciated.

**Comment by qdm12** [comment]
Have you also set `VPN_PORT_FORWARDING_PROVIDER="private internet access"`?

**Comment by xtinct101** [comment]
Thanks for the reply. I did not but have now added it and am getting this error:

```
gluetun  | 2024-06-16T22:26:19.715980602Z 2024-06-16T22:26:19Z INFO [port forwarding] starting
gluetun  | 2024-06-16T22:26:19.718359294Z panic: server name cannot be empty
gluetun  | 2024-06-16T22:26:19.718406926Z 
gluetun  | 2024-06-16T22:26:19.718420956Z goroutine 117 [running]:
gluetun  | 2024-06-16T22:26:19.718442649Z github.com/qdm12/gluetun/internal/provider/privateinternetaccess.(*Provider).PortForward(0x7f8100041380?, {0x1230458?, 0xc0000a4960?}, {{0x7f81280d58c8, 0xc000207900}, {{0x0, 0xffff0a0b8001}, 0xc000010018}, 0xc001988300, {0x0, ...}, ...})
gluetun  | 2024-06-16T22:26:19.718456186Z       github.com/qdm12/gluetun/internal/provider/privateinternetaccess/portforward.go:32 +0x6aa
gluetun  | 2024-06-16T22:26:19.718466679Z github.com/qdm12/gluetun/internal/portforward/service.(*Service).Start(0xc0001c2750, {0x1230458, 0xc0000a4960})
gluetun  | 2024-06-16T22:26:19.718474832Z       github.com/qdm12/gluetun/internal/portforward/service/start.go:32 +0x3b3
gluetun  | 2024-06-16T22:26:19.718486083Z github.com/qdm12/gluetun/internal/portforward.(*Loop).run(0xc00020d700, {0x1230458, 0xc0000a4960}, 0xc0001fc9c0?, 0xc0001fcae0, 0xc0001fca20, 0xc0001fca80)
gluetun  | 2024-06-16T22:26:19.718495178Z       github.com/qdm12/gluetun/internal/portforward/loop.go:119 +0x8f5
gluetun  | 2024-06-16T22:26:19.718506682Z created by github.com/qdm12/gluetun/internal/portforward.(*Loop).Start in goroutine 34
gluetun  | 2024-06-16T22:26:19.718514818Z       github.com/qdm12/gluetun/internal/portforward/loop.go:71 +0x20a
```

**Comment by xtinct101** [comment]
Will add the ```SERVER_NAMES=``` and try again

**Comment by xtinct101** [comment]
Ok, I've added `SERVER_NAMES=`
I then ran `docker run --rm -v ./appdata/gluetun:/gluetun qmcgaw/gluetun format-servers -private-internet-access` to get a list of servers.
Selected this server `| CA Vancouver | `ca-vancouver.privacy.network` | vancouver419 | ✅ | ✅ | ✅ |`
Used `vancouver419` as the name but still getting this error: `ERROR VPN settings: provider settings: server selection: for VPN service provider custom: the server name specified is not valid: one or more values is set but there is no possible value available`

Here is my config:
```
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=181.41.202.140
      - VPN_ENDPOINT_PORT=1337
      - WIREGUARD_PUBLIC_KEY=xxxx
      - WIREGUARD_PRIVATE_KEY=xxxx
      - PIA_PF=true
      - SERVER_NAMES=vancouver419
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER="private internet access"
      - WIREGUARD_ADDRESSES=10.11.128.3
```
Am I still missing something?

**Comment by xtinct101** [comment]
could it be an issue that in the `server.json` file all the pia servers are listed as openvpn?
```
        "vpn": "openvpn",
        "region": "CA Vancouver",
        "server_name": "vancouver419",
        "hostname": "ca-vancouver.privacy.network",
        "tcp": true,
        "udp": true,
        "port_forward": true
        ```

**Comment by qdm12** [comment]
Re-opening this since this is different than #2048 although very similar to #2147

**Comment by qdm12** [comment]
I pushed 93ed87d12bf977f74b55c5e466ef92f56de5793f which *should* allow you to set `SERVER_NAMES=somehost.privacy.com`. It's a bit ugly since it's not really for filtering a server out of a pool of servers, and really just for PIA's port forwarding but... I'm being lazy 😄 Let me know if it helps! 👍

**Comment by xtinct101** [comment]
is there a specific branch I need to use for this?

**Comment by qdm12** [comment]
Nope just the latest image, since this is really just a tiny fix and not a change/anything drastic 😉 You can `docker pull qmcgaw/gluetun`.

**Comment by xtinct101** [comment]
tried latest, doesnt hang on the same error but I now get this:
```
gluetun  | 2024-06-17T22:48:01.409292051Z 2024-06-17T22:48:01Z ERROR [vpn] getting public IP address information: fetching information: Get "https://ipinfo.io/": context canceled
gluetun  | 2024-06-17T22:48:01.409355734Z 2024-06-17T22:48:01Z ERROR [vpn] cannot get version information: Get "https://api.github.com/repos/qdm12/gluetun/commits": context canceled
gluetun  | 2024-06-17T22:48:01.409363950Z 2024-06-17T22:48:01Z INFO [port forwarding] starting
gluetun  | 2024-06-17T22:48:01.480912053Z 2024-06-17T22:48:01Z INFO [port forwarding] Found saved forwarded port data for port 25984
gluetun  | 2024-06-17T22:48:01.480973327Z 2024-06-17T22:48:01Z INFO [port forwarding] Port forwarded data expires in 62 days
gluetun  | 2024-06-17T22:48:01.509695250Z 2024-06-17T22:48:01Z WARN [dns] cannot update files: Get "https://www.internic.net/domain/named.root": dial tcp: lookup www.internic.net on 1.1.1.1:53: read udp 10.11.128.3:56432->1.1.1.1:53: i/o timeout
gluetun  | 2024-06-17T22:48:01.509752942Z 2024-06-17T22:48:01Z INFO [dns] attempting restart in 10s
```

**Comment by qdm12** [comment]
Oh that's just the VPN server not working for whatever reason. Try another server/double check your Wireguard credentials?

**Comment by xtinct101** [comment]
yeah i guess the config changes and it screws up gluetun connection. 
I updated config with latest server info and this is what I see in the logs
```
gluetun  | 2024-06-18T03:09:27.172317869Z 2024-06-18T03:09:27Z INFO [vpn] You are running on the bleeding edge of latest!
gluetun  | 2024-06-18T03:09:27.172379146Z 2024-06-18T03:09:27Z INFO [port forwarding] starting
gluetun  | 2024-06-18T03:09:27.173012454Z 2024-06-18T03:09:27Z INFO [port forwarding] Found saved forwarded port data for port 25984
gluetun  | 2024-06-18T03:09:27.173075370Z 2024-06-18T03:09:27Z INFO [port forwarding] Port forwarded data expires in 62 days
gluetun  | 2024-06-18T03:09:57.174333135Z 2024-06-18T03:09:57Z ERROR [vpn] port forwarding for the first time: binding port: Get "https://10.4.249.1:19999/bindPort?payload=<payload>&signature=<signature>": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Comment by xtinct101** [comment]
Just as reference, I've been using https://github.com/thrnz/docker-wireguard-pia for my PIA wireguard + portforwarding and it seems to connect successfully. Not sure how he/she is doing it but thought I'd just mention it in case its of any help.

**Comment by qdm12** [comment]
Perhaps try another VPN server? Would `10.4.249.1` conflict with your docker network or lan perhaps? For example `10.0.0.0/8` would conflict. If not, can you share what you get when running `docker exec gluetun /bin/sh -c "ip route show all"`, I'm curious to see, maybe my code detects wrongly the VPN server gateway IP address.

I checked thrnz/docker-wireguard-pia and it does use the same (https://github.com/thrnz/docker-wireguard-pia/blob/30fb739fd38f06086eed332fdacab88064a73701/extra/pf.sh#L123 and https://github.com/thrnz/docker-wireguard-pia/blob/30fb739fd38f06086eed332fdacab88064a73701/extra/pf.sh#L226) as in the current Gluetun code.

**Comment by xtinct101** [comment]
I tried with others, same issue. 
This is what I get when running that command
```
default via 192.168.90.1 dev eth0 
192.168.90.0/24 dev eth0 proto kernel scope link src 192.168.90.20
```
Also is there a way to get the wireguard config automatically like `thrnz/docker-wireguard-pia` as it seems after a day or 2 the config or something about the settings change and I need to manually go fix it.

**Comment by xtinct101** [comment]
Hi again,
So i've tried a few servers and I still get this error
`gluetun  | 2024-06-21T21:47:10.367471392Z 2024-06-21T21:47:10Z ERROR [vpn] port forwarding for the first time: binding port: Get "https://10.20.191.1:19999/bindPort?payload=<payload>&signature=<signature>": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

I've tried with disabling the firewall, adding outbound_subnets but always the same error.

```
├── VPN settings:
|   ├── VPN provider settings:
|   |   ├── Name: custom
|   |   ├── Server selection settings:
|   |   |   ├── VPN type: wireguard
|   |   |   ├── Target IP address: 181.41.202.239
|   |   |   ├── Server names: vancouver435
|   |   |   └── Wireguard selection settings:
|   |   |       ├── Endpoint IP address: 181.41.202.239
|   |   |       ├── Endpoint port: 1337
|   |   |       └── Server public key: xxxx
|   |   └── Automatic port forwarding settings:
|   |       ├── Redirection listening port: disabled
|   |       ├── Use code for provider: private internet access
|   |       └── Forwarded port file path: /gluetun/port.txt
|   └── Wireguard settings:
|       ├── Private key: xxxx
|       ├── Interface addresses:
|       |   └── 10.20.191.190/32
|       ├── Allowed IPs:
|       |   ├── 0.0.0.0/0
|       |   └── ::/0
|       └── Network interface: tun0
|           └── MTU: 1400
|       ├── Update period: every 24h0m0s
|       ├── Unbound settings:
|       |   ├── Authoritative servers:
|       |   |   └── cloudflare
|       |   ├── Caching: yes
|       |   ├── IPv6: no
|       |   ├── Verbosity level: 1
|       |   ├── Verbosity details level: 0
|       |   ├── Validation log level: 0
|       |   ├── System user: root
|       |   └── Allowed networks:
|       |       ├── 0.0.0.0/0
|       |       └── ::/0
|       └── DNS filtering settings:
|           ├── Block malicious: yes
|           ├── Block ads: no
|           ├── Block surveillance: no
|           └── Blocked IP networks:
|               ├── 127.0.0.1/8
|               ├── 10.0.0.0/8
|               ├── 172.16.0.0/12
|               ├── 192.168.0.0/16
|               ├── 169.254.0.0/16
|               ├── ::1/128
|               ├── fc00::/7
|               ├── fe80::/10
|               ├── ::ffff:127.0.0.1/104
|               ├── ::ffff:10.0.0.0/104
|               ├── ::ffff:169.254.0.0/112
|               ├── ::ffff:172.16.0.0/108
|               └── ::ffff:192.168.0.0/112
├── Firewall settings:
|   ├── Enabled: yes
|   ├── Debug mode: on
|   └── Outbound subnets:
|       └── 192.168.90.0/24
├── Log settings:
|   └── Log level: info
├── Health settings:
|   ├── Server listening address: 127.0.0.1:9999
|   ├── Target address: cloudflare.com:443
|   ├── Duration to wait after success: 5s
|   ├── Read header timeout: 100ms
|   ├── Read timeout: 500ms
|   └── VPN wait durations:
|       ├── Initial duration: 6s
|       └── Additional duration: 5s
├── Shadowsocks server settings:
|   └── Enabled: no
├── HTTP proxy settings:
|   └── Enabled: no
├── Control server settings:
|   ├── Listening address: :8000
|   └── Logging: yes
├── OS Alpine settings:
|   ├── Process UID: 1000
|   └── Process GID: 1000
├── Public IP settings:
|   ├── Fetching: every 12h0m0s
|   ├── IP file path: /tmp/gluetun/ip
|   └── Public IP data API: ipinfo
└── Version settings:
    └── Enabled: yes
```

**Comment by qdm12** [comment]
Sorry for the delay getting back!

My apologies the command isn't `docker exec gluetun /bin/sh -c "ip route show all"` but it is:

```sh
docker exec gluetunro /bin/sh -c "ip route show table all"
```

In my case I have a line

```
local 10.66.79.36 dev tun0 table local proto kernel scope host src 10.66.79.36
```

and the gateway should be `10.66.79.36`. I'm wondering if the gateway detected in Gluetun (in your case `10.20.191.1`) matches the gateway found in the routes.

**Comment by xtinct101** [comment]
Here's the result.
```
default dev tun0 table 51820 
192.168.90.0/24 via 192.168.90.1 dev eth0 table 199 
default via 192.168.90.1 dev eth0 table 200 
default via 192.168.90.1 dev eth0 
192.168.90.0/24 dev eth0 proto kernel scope link src 192.168.90.14 
local 10.23.219.221 dev tun0 table local proto kernel scope host src 10.23.219.221 
local 127.0.0.0/8 dev lo table local proto kernel scope host src 127.0.0.1 
local 127.0.0.1 dev lo table local proto kernel scope host src 127.0.0.1 
broadcast 127.255.255.255 dev lo table local proto kernel scope link src 127.0.0.1 
local 192.168.90.14 dev eth0 table local proto kernel scope host src 192.168.90.14 
broadcast 192.168.90.255 dev eth0 table local proto kernel scope link src 192.168.90.14
```

**Comment by qdm12** [comment]
Oh the first error

```
[vpn] getting public IP address information: fetching information: Get "https://ipinfo.io/": dial tcp: lookup ipinfo.io on 127.0.0.1:53: read udp 127.0.0.1:44865->127.0.0.1:53: i/o timeout
```

Highlights the VPN connection is not working at all. That also explains the `context deadline exceeded (Client.Timeout exceeded while awaiting headers)` error after. Do you get this i/o timeout error every time? If so, please check your credentials / update your servers / try other servers.

**Comment by xtinct101** [comment]
So i decided to completely wipe my config and start fresh.
I dont get the error above but this new error starting showing up. I'm running wireguard but it seems to want OpenVPN auth file?
```
gluetun  | 2024-07-09T14:02:18.464657561Z 2024-07-09T14:02:18Z INFO [port forwarding] starting
gluetun  | 2024-07-09T14:02:18.465275699Z 2024-07-09T14:02:18Z ERROR [vpn] port forwarding for the first time: refreshing port forward data: fetching token: getting username and password: reading OpenVPN authentication file: open /etc/openvpn/auth.conf: no such file or directory
```

**Comment by qdm12** [comment]
Whoops, fixed in 05017438145d4ed458eeaa185f981662147c05cb by adding variables `VPN_PORT_FORWARDING_USERNAME` and `VPN_PORT_FORWARDING_PASSWORD` (retro-compatible with `OPENVPN_USER` and `OPENVPN_PASSWORD` as well). Can you try pulling the latest image and set these 2 variables to see how it goes? Thanks!

**Comment by xtinct101** [comment]
grabbed the latest and added variables. I now get this error
`gluetun  | 2024-07-09T16:05:51.855626219Z 2024-07-09T16:05:51Z ERROR VPN settings: provider settings: port forwarding: port forwarding username is empty`

Here are my env variables:
```
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_PORT_FORWARDING_USERNAME=pxxxx
      - VPN_PORT_FORWARDING_PASSWORD=Cxxxx
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER="private internet access"
      - VPN_PORT_FORWARDING_STATUS_FILE=/gluetun/port.txt
      - SERVER_NAMES=panama408
      - FIREWALL_OUTBOUND_SUBNETS=192.168.90.0/24
```

**Comment by xtinct101** [comment]
using `OPENVPN_USER` and `OPENVPN_PASSWORD` seems to fix that error but I am still getting this issue:

`gluetun  | 2024-07-09T16:08:52.764591015Z 2024-07-09T16:08:52Z ERROR [vpn] port forwarding for the first time: refreshing port forward data: fetching port forwarding data: obtaining signature payload: Get "https://10.8.220.1:19999/getSignature?token=<token>": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

**Comment by jpcapone** [comment]
I am wanting to test this config out as well but I am having a hard time following which env variables to use along with which build of the image.  If anyone can spare some time to clarify that for me I would love to test as well.

**Comment by qdm12** [comment]
> grabbed the latest and added variables. I now get this error
> using OPENVPN_USER and OPENVPN_PASSWORD seems to fix that error but I am still getting this issue:

There is an important bug in the settings reading system, I'm working on a fix first.

@jpcapone 

> I am wanting to test this config out as well but I am having a hard time following which env variables to use along with which build of the image. If anyone can spare some time to clarify that for me I would love to test as well.

Thanks for trying to help out debug this 😉 This is the latest image `qmcgaw/gluetun`. Right now you can use `OPENVPN_USER` and `OPENVPN_PASSWORD` to set your PIA credentials for port forwarding if you use wireguard+custom provider.

**Comment by jpcapone** [comment]
Using these variabled
```
- VPN_SERVICE_PROVIDER=custom
- VPN_TYPE=wireguard
- OPENVPN_USER=xxxxxxxx
- OPENVPN_PASSWORD=xxxxxxx
- VPN_PORT_FORWARDING=on
- SERVER_NAMES=panama408
```
I am getting these errors:

```
2024-07-11T17:50:09Z WARN You are using the old environment variable OPENVPN_USER, please consider changing it to VPN_PORT_FORWARDING_USERNAME
2024-07-11T17:50:09Z WARN You are using the old environment variable OPENVPN_PASSWORD, please consider changing it to VPN_PORT_FORWARDING_PASSWORD
2024-07-11T17:50:09Z INFO [routing] default route found: interface eth0, gateway 172.29.0.1, assigned IP 172.29.0.2 and family v4
2024-07-11T17:50:09Z INFO [routing] local ethernet link found: eth0
2024-07-11T17:50:09Z INFO [routing] local ipnet found: 172.29.0.0/16
2024-07-11T17:50:09Z INFO [firewall] enabling...
2024-07-11T17:50:09Z INFO [firewall] enabled successfully
2024-07-11T17:50:10Z INFO [storage] creating /gluetun/servers.json with 19425 hardcoded servers
2024-07-11T17:50:10Z ERROR VPN settings: provider settings: server selection: Wireguard server selection settings: endpoint IP is not set
2024-07-11T17:50:10Z INFO Shutdown successful
```

I am gonna keep trying different things but thats where I am at right now.

**Comment by xtinct101** [comment]
unless you're supplying Gluetun with a wg0 file you will need to setup all the wireguard endpoints.
```
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - OPENVPN_USER=xxxxxxxx
      - OPENVPN_PASSWORD=xxxxxxx
      - SERVER_NAMES=panama408
      - VPN_ENDPOINT_IP=xxxx
      - VPN_ENDPOINT_PORT=xxxx
      - WIREGUARD_PUBLIC_KEY=xxxx
      - WIREGUARD_PRIVATE_KEY=xxxx
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER="private internet access"
      - WIREGUARD_ADDRESSES=xxxx
```

**Comment by jpcapone** [comment]
Thank you so much.  Ok so using the variables below:

```
VPN_SERVICE_PROVIDER=custom
VPN_TYPE=wireguard
OPENVPN_USER=pxxxx
OPENVPN_PASSWORD=xxxxxxx
SERVER_NAMES=bahamas402
VPN_ENDPOINT_IP=95.181.238.104
VPN_ENDPOINT_PORT=1337
WIREGUARD_PUBLIC_KEY=xxxxxx
WIREGUARD_PRIVATE_KEY=xxxxxx
VPN_PORT_FORWARDING=on
VPN_PORT_FORWARDING_PROVIDER="private internet access"
WIREGUARD_ADDRESSES=xx.xx.xx.xx/32
```

Now with the settings above I am only unsure about the WIREGUARD_ADDRESSES value 
In the conf file it appears that only the IP listed for "Address" makes sense and I added the /32 from what I have gathered from other posts.


```
2024-07-11T21:54:16Z INFO [vpn] starting
2024-07-11T21:54:16Z INFO [firewall] allowing VPN connection...
2024-07-11T21:54:16Z INFO [wireguard] Using available kernelspace implementation
2024-07-11T21:54:16Z INFO [wireguard] Connecting to 95.181.238.104:1337
2024-07-11T21:54:16Z INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o timeout errors indicate the Wireguard connection is not working.
2024-07-11T21:54:31Z ERROR [vpn] getting public IP address information: fetching information: Get "https://ipinfo.io/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2024-07-11T21:54:31Z INFO [port forwarding] starting
2024-07-11T21:54:46Z ERROR [vpn] port forwarding for the first time: refreshing port forward data: fetching token: Post "https://www.privateinternetaccess.com/api/client/v2/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2024-07-11T21:54:47Z INFO [healthcheck] program has been unhealthy for 26s: restarting VPN
2024-07-11T21:54:47Z INFO [healthcheck] 👉 See https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md
2024-07-11T21:54:47Z INFO [healthcheck] DO NOT OPEN AN ISSUE UNLESS YOU READ AND TRIED EACH POSSIBLE SOLUTION
2024-07-11T21:54:47Z INFO [vpn] stopping
2024-07-11T21:54:47Z INFO [vpn] starting
2024-07-11T21:54:47Z INFO [firewall] allowing VPN connection...
2024-07-11T21:54:47Z INFO [wireguard] Using available kernelspace implementation
2024-07-11T21:54:47Z INFO [wireguard] Connecting to 95.181.238.104:1337
2024-07-11T21:54:47Z INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o timeout errors indicate the Wireguard connection is not working.
2024-07-11T21:54:49Z INFO [dns] downloading DNS over TLS cryptographic files
2024-07-11T21:55:02Z ERROR [vpn] getting public IP address information: fetching information: Get "https://ipinfo.io/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2024-07-11T21:55:02Z INFO [port forwarding] starting
2024-07-11T21:55:04Z WARN [dns] cannot update files: Get "https://www.internic.net/domain/named.root": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2024-07-11T21:55:04Z INFO [dns] attempting restart in 1m20s
2024-07-11T21:55:17Z ERROR [vpn] port forwarding for the first time: refreshing port forward data: fetching token: Post "https://www.privateinternetaccess.com/api/client/v2/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2024-07-11T21:55:27Z INFO [healthcheck] program has been unhealthy for 31s: restarting VPN
2024-07-11T21:55:27Z INFO [healthcheck] 👉 See https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md
2024-07-11T21:55:27Z INFO [healthcheck] DO NOT OPEN AN ISSUE UNLESS YOU READ AND TRIED EACH POSSIBLE SOLUTION
2024-07-11T21:55:27Z INFO [vpn] stopping
```

The only other thing I think I can do on my side is mount a volume for Gluetun as I currently don't have one.  I am open to any other suggestions.

**Comment by xtinct101** [comment]
I use mine without the /32 or anything. `WIREGUARD_ADDRESSES=xx.xx.xx.xx` 
Also, I would first try disabling the port forwarding to make sure the vpn is working without.
Second, `2024-07-11T21:55:02Z ERROR [vpn] getting public IP address information: fetching information: Get "https://ipinfo.io/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)` I learnt that this error meant that the VPN isn't working. Where did you get the pia conf file from as I've noticed that some of the servers for pia from gluetun seem outdated and don't necessarily work. I use this to generate correct wg0 conf files. https://github.com/pia-foss

**Comment by jpcapone** [comment]
Thanks. I used https://github.com/pia-foss/manual-connections to generate the conf file.  
![image](https://github.com/user-attachments/assets/f41dce3f-970e-4eac-8c8e-52ffdd8a654a)

 I did remove the /32 and disabled port forwarding by removing the variable and the same error shows up again.  Any other ideas?

**Comment by xtinct101** [comment]
I would just double check your user/pass, public and private keys. 
If that doesn't work, try a different server. I know for sure, panama works so maybe give that a shot.

**Comment by xtinct101** [comment]
also, since you're generating the wg0 file, you can feed it directly to gluetun so you dont need to figure out those settings and would just need these ones for testing connectivity.
```
- VPN_SERVICE_PROVIDER=custom
- VPN_TYPE=wireguard
- SERVER_NAMES=panama408
```

Make sure to map a volume to the wg0 file like this.
`- xxxx/gluetun/wg0.conf:/gluetun/wireguard/wg0.conf`

**Comment by jpcapone** [comment]
for `FIREWALL_OUTBOUND_SUBNETS` would that range need to be my LAN or the container network?

**Comment by xtinct101** [comment]
For me it's the container network.

**Comment by jpcapone** [comment]
Ok I have mounted the actual wg0.cnf file which was created with the panama server and using the variables below - take note no VPN forwarding
```
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - SERVER_NAMES=panama408
      - `FIREWALL_OUTBOUND_SUBNETS=172.29.0.0/24
```
I get the following:
```
Running version latest built on 2024-07-09T14:47:46.048Z (commit 0501743)

🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
🐛 Bug? https://github.com/qdm12/gluetun/issues/new
✨ New feature? https://github.com/qdm12/gluetun/issues/new
☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
💻 Email? quentin.mcgaw@gmail.com
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2024-07-12T00:05:41Z WARN You are using the old environment variable OPENVPN_USER, please consider changing it to VPN_PORT_FORWARDING_USERNAME
2024-07-12T00:05:41Z WARN You are using the old environment variable OPENVPN_PASSWORD, please consider changing it to VPN_PORT_FORWARDING_PASSWORD
2024-07-12T00:05:41Z INFO [routing] default route found: interface eth0, gateway 172.29.0.1, assigned IP 172.29.0.2 and family v4
2024-07-12T00:05:41Z INFO [routing] local ethernet link found: eth0
2024-07-12T00:05:41Z INFO [routing] local ipnet found: 172.29.0.0/16
2024-07-12T00:05:41Z INFO [firewall] enabling...
2024-07-12T00:05:41Z INFO [firewall] enabled successfully
2024-07-12T00:05:41Z INFO [storage] creating /gluetun/servers.json with 19425 hardcoded servers
2024-07-12T00:05:41Z INFO Alpine version: 3.19.2
2024-07-12T00:05:41Z INFO OpenVPN 2.5 version: 2.5.10
2024-07-12T00:05:41Z INFO OpenVPN 2.6 version: 2.6.11
2024-07-12T00:05:41Z INFO Unbound version: 1.20.0
2024-07-12T00:05:41Z INFO IPtables version: v1.8.10
2024-07-12T00:05:41Z INFO Settings summary:
├── VPN settings:
|   ├── VPN provider settings:
|   |   ├── Name: custom
|   |   └── Server selection settings:
|   |       ├── VPN type: wireguard
|   |       ├── Target IP address: 91.90.126.91
|   |       ├── Server names: panama408
|   |       └── Wireguard selection settings:
|   |           ├── Endpoint IP address: 91.90.126.91
|   |           ├── Endpoint port: 1337
|   |           └── Server public key: 3SzMcnATWE/EoEhNeZ9r4xa8NZ/u7bDJptE1xFflaBE=
|   └── Wireguard settings:
|       ├── Private key: QP6...nI=
|       ├── Interface addresses:
|       |   └── 10.11.153.88/32
|       ├── Allowed IPs:
|       |   ├── 0.0.0.0/0
|       |   └── ::/0
|       └── Network interface: tun0
|           └── MTU: 1400
├── DNS settings:
|   ├── Keep existing nameserver(s): no
|   ├── DNS server address to use: 127.0.0.1
|   └── DNS over TLS settings:
|       ├── Enabled: yes
|       ├── Update period: every 24h0m0s
|       ├── Unbound settings:
|       |   ├── Authoritative servers:
|       |   |   └── cloudflare
|       |   ├── Caching: yes
|       |   ├── IPv6: no
|       |   ├── Verbosity level: 1
|       |   ├── Verbosity details level: 0
|       |   ├── Validation log level: 0
|       |   ├── System user: root
|       |   └── Allowed networks:
|       |       ├── 0.0.0.0/0
|       |       └── ::/0
|       └── DNS filtering settings:
|           ├── Block malicious: yes
|           ├── Block ads: no
|           ├── Block surveillance: no
|           └── Blocked IP networks:
|               ├── 127.0.0.1/8
|               ├── 10.0.0.0/8
|               ├── 172.16.0.0/12
|               ├── 192.168.0.0/16
|               ├── 169.254.0.0/16
|               ├── ::1/128
|               ├── fc00::/7
|               ├── fe80::/10
|               ├── ::ffff:127.0.0.1/104
|               ├── ::ffff:10.0.0.0/104
|               ├── ::ffff:169.254.0.0/112
|               ├── ::ffff:172.16.0.0/108
|               └── ::ffff:192.168.0.0/112
├── Firewall settings:
|   ├── Enabled: yes
|   └── Outbound subnets:
|       └── 172.29.0.0/24
├── Log settings:
|   └── Log level: info
├── Health settings:
|   ├── Server listening address: 127.0.0.1:9999
|   ├── Target address: cloudflare.com:443
|   ├── Duration to wait after success: 5s
|   ├── Read header timeout: 100ms
|   ├── Read timeout: 500ms
|   └── VPN wait durations:
|       ├── Initial duration: 6s
|       └── Additional duration: 5s
├── Shadowsocks server settings:
|   └── Enabled: no
├── HTTP proxy settings:
|   └── Enabled: no
├── Control server settings:
|   ├── Listening address: :8000
|   └── Logging: yes
├── OS Alpine settings:
|   ├── Process UID: 1000
|   └── Process GID: 1000
├── Public IP settings:
|   ├── Fetching: every 12h0m0s
|   ├── IP file path: /tmp/gluetun/ip
|   └── Public IP data API: ipinfo
└── Version settings:
    └── Enabled: yes
2024-07-12T00:05:41Z INFO [routing] default route found: interface eth0, gateway 172.29.0.1, assigned IP 172.29.0.2 and family v4
2024-07-12T00:05:41Z INFO [routing] adding route for 0.0.0.0/0
2024-07-12T00:05:41Z INFO [firewall] setting allowed subnets...
2024-07-12T00:05:41Z INFO [routing] default route found: interface eth0, gateway 172.29.0.1, assigned IP 172.29.0.2 and family v4
2024-07-12T00:05:41Z INFO [routing] adding route for 172.29.0.0/24
2024-07-12T00:05:41Z INFO TUN device is not available: open /dev/net/tun: no such file or directory; creating it...
2024-07-12T00:05:41Z INFO [dns] using plaintext DNS at address 1.1.1.1
2024-07-12T00:05:41Z INFO [http server] http server listening on [::]:8000
2024-07-12T00:05:41Z INFO [healthcheck] listening on 127.0.0.1:9999
2024-07-12T00:05:41Z INFO [firewall] allowing VPN connection...
2024-07-12T00:05:41Z INFO [wireguard] Using available kernelspace implementation
2024-07-12T00:05:41Z INFO [wireguard] Connecting to 91.90.126.91:1337
2024-07-12T00:05:41Z INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o timeout errors indicate the Wireguard connection is not working.
2024-07-12T00:05:41Z INFO [dns] downloading DNS over TLS cryptographic files
2024-07-12T00:05:51Z INFO [healthcheck] program has been unhealthy for 6s: restarting VPN
2024-07-12T00:05:51Z INFO [healthcheck] 👉 See https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md
2024-07-12T00:05:51Z INFO [healthcheck] DO NOT OPEN AN ISSUE UNLESS YOU READ AND TRIED EACH POSSIBLE SOLUTION
2024-07-12T00:05:51Z INFO [vpn] stopping
2024-07-12T00:05:51Z ERROR [vpn] getting public IP address information: fetching information: Get "https://ipinfo.io/": context canceled
2024-07-12T00:05:51Z ERROR [vpn] cannot get version information: Get "https://api.github.com/repos/qdm12/gluetun/commits": context canceled
2024-07-12T00:05:51Z INFO [vpn] starting
2024-07-12T00:05:51Z INFO [firewall] allowing VPN connection...
2024-07-12T00:05:51Z INFO [wireguard] Using available kernelspace implementation
2024-07-12T00:05:51Z INFO [wireguard] Connecting to 91.90.126.91:1337
2024-07-12T00:05:51Z INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o timeout errors indicate the Wireguard connection is not working.
2024-07-12T00:05:56Z WARN [dns] cannot update files: Get "https://www.internic.net/domain/named.root": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2024-07-12T00:05:56Z INFO [dns] attempting restart in 10s
```

I am gonna keep trying stuff but I would appreciate any suggestions....

**Comment by xtinct101** [comment]
can you paste you docker compose?

**Comment by jpcapone** [comment]
Here is the full docker compose

```
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - SERVER_NAMES=panama408
      - FIREWALL_OUTBOUND_SUBNETS=172.29.0.0/24
      - SHADOWSOCKS=on
      - SHADOWSOCKS_PASSWORD=xxxxx
      - HTTP_CONTROL_SERVER_ADDRESS=:8000
    volumes:
      - /etc/wireguard/wg0.conf:/gluetun/wireguard/wg0.conf
    ports:
      - 8388:8388/tcp
      - 8388:8388/udp
      - 8180:8180
      - 8000:8000
  qbittorrent:
    image: linuxserver/qbittorrent #orig: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent1
    network_mode: service:gluetun # NOTE: network mode while inside the container, you  should still be able to talk to this service from your regular LAN via the host-IP
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/New_York
      - WEBUI_PORT=8180
    volumes:
      - /var/lib/docker/volumes/wireguard/qbittorrent:/config # extra measure inside QB 'bind' to the WG IP you get
      - /media/Share/Complete/qbittorrent:/media/Share/Complete/qbittorrent
    restart: unless-stopped # no | always | on-failure | unless-stopped
```

**Comment by xtinct101** [comment]
add
```    
devices:
      - /dev/net/tun:/dev/net/tun
```

**Comment by jpcapone** [comment]
I was wondering about that one.  I added it and that error disappears but the error remains:

```
2024-07-12T13:59:22Z INFO [routing] default route found: interface eth0, gateway 172.29.0.1, assigned IP 172.29.0.2 and family v4
2024-07-12T13:59:22Z INFO [routing] adding route for 0.0.0.0/0
2024-07-12T13:59:22Z INFO [firewall] setting allowed subnets...
2024-07-12T13:59:22Z INFO [routing] default route found: interface eth0, gateway 172.29.0.1, assigned IP 172.29.0.2 and family v4
2024-07-12T13:59:22Z INFO [routing] adding route for 172.29.0.0/24
2024-07-12T13:59:22Z INFO [dns] using plaintext DNS at address 1.1.1.1
2024-07-12T13:59:22Z INFO [http server] http server listening on [::]:8000
2024-07-12T13:59:22Z INFO [firewall] allowing VPN connection...
2024-07-12T13:59:22Z INFO [healthcheck] listening on 127.0.0.1:9999
2024-07-12T13:59:22Z INFO [shadowsocks] listening TCP on [::]:8388
2024-07-12T13:59:22Z INFO [shadowsocks] listening UDP on [::]:8388
2024-07-12T13:59:22Z INFO [wireguard] Using available kernelspace implementation
2024-07-12T13:59:22Z INFO [wireguard] Connecting to 91.90.126.40:1337
2024-07-12T13:59:22Z INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o timeout errors indicate the Wireguard connection is not working.
2024-07-12T13:59:22Z INFO [dns] downloading DNS over TLS cryptographic files
2024-07-12T13:59:32Z INFO [healthcheck] program has been unhealthy for 6s: restarting VPN
2024-07-12T13:59:32Z INFO [healthcheck] 👉 See https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md
2024-07-12T13:59:32Z INFO [healthcheck] DO NOT OPEN AN ISSUE UNLESS YOU READ AND TRIED EACH POSSIBLE SOLUTION
2024-07-12T13:59:32Z INFO [vpn] stopping
2024-07-12T13:59:32Z ERROR [vpn] getting public IP address information: fetching information: Get "https://ipinfo.io/": context canceled
2024-07-12T13:59:32Z ERROR [vpn] cannot get version information: Get "https://api.github.com/repos/qdm12/gluetun/commits": context canceled
2024-07-12T13:59:32Z INFO [vpn] starting
2024-07-12T13:59:32Z INFO [firewall] allowing VPN connection...
2024-07-12T13:59:32Z INFO [wireguard] Using available kernelspace implementation
2024-07-12T13:59:32Z INFO [wireguard] Connecting to 91.90.126.40:1337
2024-07-12T13:59:32Z INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o timeout errors indicate the Wireguard connection is not working.
2024-07-12T13:59:37Z WARN [dns] cannot update files: Get "https://www.internic.net/domain/named.root": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2024-07-12T13:59:37Z INFO [dns] attempting restart in 10s
2024-07-12T13:59:44Z INFO [healthcheck] program has been unhealthy for 11s: restarting VPN
2024-07-12T13:59:44Z INFO [healthcheck] 👉 See https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md
2024-07-12T13:59:44Z INFO [healthcheck] DO NOT OPEN AN ISSUE UNLESS YOU READ AND TRIED EACH POSSIBLE SOLUTION
2024-07-12T13:59:44Z INFO [vpn] stopping
```

**Comment by jpcapone** [comment]
I switched the server to Au Perth and it worked!  But when I turned on port forwarding
```
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER="private internet access"
```

 I got this error

```
2024-07-12T15:50:55Z WARN You are using the old environment variable OPENVPN_USER, please consider changing it to VPN_PORT_FORWARDING_USERNAME
2024-07-12T15:50:55Z WARN You are using the old environment variable OPENVPN_PASSWORD, please consider changing it to VPN_PORT_FORWARDING_PASSWORD
2024-07-12T15:50:55Z INFO [routing] default route found: interface eth0, gateway 172.29.0.1, assigned IP 172.29.0.2 and family v4
2024-07-12T15:50:55Z INFO [routing] local ethernet link found: eth0
2024-07-12T15:50:55Z INFO [routing] local ipnet found: 172.29.0.0/16
2024-07-12T15:50:55Z INFO [firewall] enabling...
2024-07-12T15:50:55Z INFO [firewall] enabled successfully
2024-07-12T15:50:55Z INFO [storage] creating /gluetun/servers.json with 19425 hardcoded servers
2024-07-12T15:50:55Z ERROR VPN settings: provider settings: port forwarding: port forwarding username is empty
2024-07-12T15:50:55Z INFO Shutdown successful
```
I added the variables below:
```
      - VPN_PORT_FORWARDING_USERNAME=pxxxxxx
      - VPN_PORT_FORWARDING_PASSWORD=xxxxxx
```
and got the same error.  So my current compose file looks like

```
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - SERVER_NAMES=perth403
      - FIREWALL_OUTBOUND_SUBNETS=172.29.0.0/24
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER="private internet access"
      - VPN_PORT_FORWARDING_USERNAME=xxxxxxxx
      - VPN_PORT_FORWARDING_PASSWORD=xxxxxxxx
      - SHADOWSOCKS=on
      - SHADOWSOCKS_PASSWORD=xxxxxxxx
      - HTTP_CONTROL_SERVER_ADDRESS=:8000
    volumes:
      - /etc/wireguard/wg0.conf:/gluetun/wireguard/wg0.conf
    ports:
      - 8388:8388/tcp
      - 8388:8388/udp
      - 8180:8180
      - 8000:8000
  qbittorrent:
    image: linuxserver/qbittorrent #orig: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent1
    network_mode: service:gluetun # NOTE: network mode while inside the container, you  should still be able to talk to this service from your regular LAN via the host-IP
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/New_York
      - WEBUI_PORT=8180
    volumes:
      - /var/lib/docker/volumes/wireguard/qbittorrent:/config # extra measure inside QB 'bind' to the WG IP you get
      - /media/Share/Complete/qbittorrent:/media/Share/Complete/qbittorrent
    restart: unless-stopped # no | always | on-failure | unless-stopped
```

**Comment by xtinct101** [comment]
use these for now as the new ones dont work.
```
      - OPENVPN_USER=
      - OPENVPN_PASSWORD=
      
```

**Comment by jpcapone** [comment]
Ok I missed your response before I switched back to using the variables instead of the mounted file. either way i got the same result.  i got further but it seems to be failing on the port forwarding part
```
2024-07-12T16:33:44Z INFO [routing] default route found: interface eth0, gateway 172.29.0.1, assigned IP 172.29.0.2 and family v4
2024-07-12T16:33:44Z INFO [routing] adding route for 0.0.0.0/0
2024-07-12T16:33:44Z INFO [firewall] setting allowed subnets...
2024-07-12T16:33:44Z INFO [routing] default route found: interface eth0, gateway 172.29.0.1, assigned IP 172.29.0.2 and family v4
2024-07-12T16:33:44Z INFO [routing] adding route for 172.29.0.0/24
2024-07-12T16:33:44Z INFO [dns] using plaintext DNS at address 1.1.1.1
2024-07-12T16:33:44Z INFO [http server] http server listening on [::]:8000
2024-07-12T16:33:44Z INFO [firewall] allowing VPN connection...
2024-07-12T16:33:44Z INFO [healthcheck] listening on 127.0.0.1:9999
2024-07-12T16:33:44Z INFO [shadowsocks] listening TCP on [::]:8388
2024-07-12T16:33:44Z INFO [shadowsocks] listening UDP on [::]:8388
2024-07-12T16:33:44Z INFO [wireguard] Using available kernelspace implementation
2024-07-12T16:33:44Z INFO [wireguard] Connecting to 179.61.228.3:1337
2024-07-12T16:33:44Z INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o timeout errors indicate the Wireguard connection is not working.
2024-07-12T16:33:44Z INFO [dns] downloading DNS over TLS cryptographic files
2024-07-12T16:33:45Z INFO [healthcheck] healthy!
2024-07-12T16:33:48Z INFO [dns] downloading hostnames and IP block lists
2024-07-12T16:33:54Z INFO [dns] init module 0: validator
2024-07-12T16:33:54Z INFO [dns] init module 1: iterator
2024-07-12T16:33:54Z INFO [dns] start of service (unbound 1.20.0).
2024-07-12T16:33:55Z INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2024-07-12T16:33:58Z INFO [dns] ready
2024-07-12T16:33:59Z INFO [healthcheck] healthy!
2024-07-12T16:34:00Z INFO [ip getter] Public IP address is 179.61.228.3 (Australia, Western Australia, Perth)
2024-07-12T16:34:02Z INFO [vpn] You are running on the bleeding edge of latest!
2024-07-12T16:34:02Z INFO [port forwarding] starting
2024-07-12T16:34:34Z ERROR [vpn] port forwarding for the first time: refreshing port forward data: fetching port forwarding data: obtaining signature payload: Get "https://10.2.157.1:19999/getSignature?token=<token>": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Comment by xtinct101** [comment]
Yep and that’s the issue we’re trying to fix. Port forwarding is not working on PIA and wireguard. 
So now you’re exactly where I am.

**Comment by jpcapone** [comment]
Hahahahaha!  Well thanks for helping me get here.  Ill keep my eye on this thread!!

**Comment by jpcapone** [comment]
> Yep and that’s the issue we’re trying to fix. Port forwarding is not working on PIA and wireguard. So now you’re exactly where I am.

Its crazy how you get different results from different servers.  I pulled a list of PIA servers that support port forwarding and Panama, Bahamas are both listed but Au Perth is the one that worked for me.

**Comment by xtinct101** [comment]
I love Gluetun and can't wait to get it sorted but until then you can use 
`https://github.com/thrnz/docker-wireguard-pia` to get PIA wireguard with port forwarding.

**Comment by qdm12** [comment]
### @xtinct101 @jpcapone 

Two questions:

1. When running Gluetun+Wireguard+Custom(PIA), what do you get from `docker exec gluetun traceroute -4 -m 1 -i tun0 privateinternetaccess.com`?
2. I've been reviewing the code in https://github.com/thrnz/docker-wireguard-pia and it seems the same as Gluetun's one. For the same Wireguard  server, what do you have logged by [this line](https://github.com/thrnz/docker-wireguard-pia/blob/5c6fd5dc6dcd204c6a6a7c56e5637928446ede0b/extra/pf.sh#L199C3-L199C48) in the form `$(date): Using $api_ip as API endpoint` (if it shows at all)? I'm curious to find the difference, I would guess this is really just the wrong IP address (which oddly works for OpenVPN but not for Wireguard servers).

> There is an important bug in the settings reading system, I'm working on a fix first

This is fixed in 9d50c2353204a6d497b94fbfa96423c8bda5f529 (bug was introduced on the master branch after the last release v3.38.0). Thanks for taking the time to mention it didn't work! Now the new variables will work (`VPN_PORT_FORWARDING_USERNAME` and `VPN_PORT_FORWARDING_PASSWORD`).

@xtinct101 Thank you for helping out @jpcapone 👍 However, I marked the few comments as off-topic since this is about bringing PIA port forwarding to life when using Wireguard (custom provider), and it's hard to focus on what's what otherwise. Anyway it seems it's resolved so congrats on that 💯

Also FYI & AFAIK:

> For me it's the container network.

The container network Gluetun is part of is automatically allowed traffic with (at least it should!), so you should not have to set this. If it's your LAN, you might need to though.

**Comment by xtinct101** [comment]
Yeah no worries regarding off-topic was just trying to get @jpcapone to at up and running without port forwarding.

1. When I run that command I get this.
```
traceroute to privateinternetaccess.com (172.64.151.73), 1 hops max, 46 byte packets
 1  10.8.128.1 (10.8.128.1)  20.003 ms  21.773 ms  22.157 ms```
 2. It doesn't seem to log it but what is perhaps useful is when I looked at the wg0 from `thrnz/docker-wireguard-pia` the api ip is `10.9.128.1` which is different then what gluetun traces above.
 Here is the full log from `docker-wireguard` if there might be anything useful.
 ```
 piavpn  | 2024-07-11T10:01:47.560373248Z Using PIA DNS servers: 10.0.0.243,10.0.0.242
piavpn  | 2024-07-11T10:01:47.561243535Z Port forwarding is available at this location
piavpn  | 2024-07-11T10:01:47.561260461Z Successfully generated /etc/wireguard/wg0.conf
piavpn  | 2024-07-11T10:01:47.563301712Z Thu Jul 11 10:01:47 UTC 2024: Bringing up WireGuard interface wg0
piavpn  | 2024-07-11T10:01:47.569304634Z [#] ip link add wg0 type wireguard
piavpn  | 2024-07-11T10:01:47.570147192Z [#] wg setconf wg0 /dev/fd/63
piavpn  | 2024-07-11T10:01:47.570730543Z [#] ip -4 address add 10.9.175.227 dev wg0
piavpn  | 2024-07-11T10:01:47.572763140Z [#] ip link set mtu 1420 up dev wg0
piavpn  | 2024-07-11T10:01:47.573644819Z [#] resolvconf -a wg0 -m 0 -x
piavpn  | 2024-07-11T10:01:47.575603154Z could not detect a useable init system
piavpn  | 2024-07-11T10:01:47.584086821Z [#] wg set wg0 fwmark 51820
piavpn  | 2024-07-11T10:01:47.584375038Z [#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
piavpn  | 2024-07-11T10:01:47.584740790Z [#] ip -4 rule add not fwmark 51820 table 51820
piavpn  | 2024-07-11T10:01:47.585153558Z [#] ip -4 rule add table main suppress_prefixlength 0
piavpn  | 2024-07-11T10:01:47.586676679Z [#] iptables-restore -n
piavpn  | 2024-07-11T10:01:47.587637142Z 
piavpn  | 2024-07-11T10:01:47.587878209Z interface: wg0
piavpn  | 2024-07-11T10:01:47.587901118Z   public key: xxxx
piavpn  | 2024-07-11T10:01:47.587902469Z   private key: (hidden)
piavpn  | 2024-07-11T10:01:47.587903680Z   listening port: 47734
piavpn  | 2024-07-11T10:01:47.587904861Z   fwmark: 0xca6c
piavpn  | 2024-07-11T10:01:47.587906077Z 
piavpn  | 2024-07-11T10:01:47.587907110Z peer: xxxx
piavpn  | 2024-07-11T10:01:47.587908230Z   endpoint: 91.90.126.60:1337
piavpn  | 2024-07-11T10:01:47.587909278Z   allowed ips: 0.0.0.0/0
piavpn  | 2024-07-11T10:01:47.587910306Z   transfer: 0 B received, 148 B sent
piavpn  | 2024-07-11T10:01:47.587911432Z   persistent keepalive: every 25 seconds
piavpn  | 2024-07-11T10:01:47.587933702Z 
piavpn  | 2024-07-11T10:01:47.588244456Z Thu Jul 11 10:01:47 UTC 2024: WireGuard successfully started
piavpn  | 2024-07-11T10:01:47.685488578Z Thu Jul 11 10:01:47 UTC 2024: Allowing network access to 192.168.90.19/24 on eth0
piavpn  | 2024-07-11T10:01:47.694955669Z Thu Jul 11 10:01:47 UTC 2024: Firewall enabled: Blocking non-WireGuard traffic
piavpn  | 2024-07-11T10:01:47.703866050Z Thu Jul 11 10:01:47 UTC 2024: Allowing network access to 192.168.50.0/24 on eth0
piavpn  | 2024-07-11T10:01:47.710342613Z Thu Jul 11 10:01:47 UTC 2024: Adding route to 192.168.50.0/24
piavpn  | 2024-07-11T10:01:47.714226853Z Thu Jul 11 10:01:47 UTC 2024: Allowing network access to 192.168.90.0/24 on eth0
piavpn  | 2024-07-11T10:01:47.720479613Z Thu Jul 11 10:01:47 UTC 2024: Adding route to 192.168.90.0/24
piavpn  | 2024-07-11T10:01:47.722536902Z RTNETLINK answers: File exists
piavpn  | 2024-07-11T10:01:47.730071795Z Thu Jul 11 10:01:47 UTC 2024: Starting port forward script
piavpn  | 2024-07-11T10:01:47.736102890Z Thu Jul 11 10:01:47 UTC 2024: Verifying API requests. CN: panama406
piavpn  | 2024-07-11T10:01:47.738721823Z Thu Jul 11 10:01:47 UTC 2024: Getting PF token
piavpn  | 2024-07-11T10:01:47.740129642Z Thu Jul 11 10:01:47 UTC 2024: Reusing previous PF token
piavpn  | 2024-07-11T10:01:52.935910254Z Thu Jul 11 10:01:52 UTC 2024: Obtained PF token. Expires at 2024-08-31T04:28:30.946050398Z
piavpn  | 2024-07-11T10:01:52.936192158Z Thu Jul 11 10:01:52 UTC 2024: Server accepted PF bind
piavpn  | 2024-07-11T10:01:52.936515877Z Thu Jul 11 10:01:52 UTC 2024: Forwarding on port 24737
piavpn  | 2024-07-11T10:01:52.936793219Z Thu Jul 11 10:01:52 UTC 2024: Rebind interval: 900 seconds
piavpn  | 2024-07-11T10:01:52.937022726Z Thu Jul 11 10:01:52 UTC 2024: Port dumped to /pia-shared/port.txt
piavpn  | 2024-07-11T10:01:52.937352090Z Thu Jul 11 10:01:52 UTC 2024: This script should remain running to keep the forwarded port alive
piavpn  | 2024-07-11T10:01:52.937613422Z Thu Jul 11 10:01:52 UTC 2024: Press Ctrl+C to exit
piavpn  | 2024-07-11T10:01:52.938034803Z Thu Jul 11 10:01:52 UTC 2024: Running /scripts/pf_success.sh
piavpn  | 2024-07-11T10:01:52.940007073Z Thu Jul 11 10:01:52 UTC 2024: Allowing incoming traffic on port 24737
```

**Comment by qdm12** [comment]
> 2\. when I looked at the wg0 from `thrnz/docker-wireguard-pia` the api ip is `10.9.128.1` which is different then what gluetun traces above.

Oh wait, are all PIA Wireguard configurations coming with a `#pf api ip: 1.2.3.4`??? Because I see this line now https://github.com/thrnz/docker-wireguard-pia/blob/5c6fd5dc6dcd204c6a6a7c56e5637928446ede0b/run#L280C19-L280C26 and it looks like it? If so, I could parse it out. I am guessing the code they have [here](https://github.com/thrnz/docker-wireguard-pia/blob/5c6fd5dc6dcd204c6a6a7c56e5637928446ede0b/extra/pf.sh#L188-L200) doesn't actually work, same as Gluetun. So possibly we cannot auto-magically determine the API IP address 🤔 Alternatively, would you be ok having a new option `PORT_FORWARDING_API_IP` which you can set to `10.9.128.1` for example?

**Comment by dreary-ennui** [comment]
> > 2. when I looked at the wg0 from `thrnz/docker-wireguard-pia` the api ip is `10.9.128.1` which is different then what gluetun traces above.
> 
> Oh wait, are all PIA Wireguard configurations coming with a `#pf api ip: 1.2.3.4`??? Because I see this line now https://github.com/thrnz/docker-wireguard-pia/blob/5c6fd5dc6dcd204c6a6a7c56e5637928446ede0b/run#L280C19-L280C26 and it looks like it? If so, I could parse it out. I am guessing the code they have [here](https://github.com/thrnz/docker-wireguard-pia/blob/5c6fd5dc6dcd204c6a6a7c56e5637928446ede0b/extra/pf.sh#L188-L200) doesn't actually work, same as Gluetun. So possibly we cannot auto-magically determine the API IP address 🤔 Alternatively, would you be ok having a new option `PORT_FORWARDING_API_IP` which you can set to `10.9.128.1` for example?

In my own usage of thrnz's docker-wireguard-pia, I do have a `#pf api ip: x.x.x.x` line, but it's not `10.9.128.1`. Perhaps it changes based on server selection or some other factor? If so, I'd not want to have to hard code it in an environment variable, but rather some automated fashion of determining it.

**Comment by xtinct101** [comment]
> > 2. when I looked at the wg0 from `thrnz/docker-wireguard-pia` the api ip is `10.9.128.1` which is different then what gluetun traces above.
> 
> Oh wait, are all PIA Wireguard configurations coming with a `#pf api ip: 1.2.3.4`??? Because I see this line now https://github.com/thrnz/docker-wireguard-pia/blob/5c6fd5dc6dcd204c6a6a7c56e5637928446ede0b/run#L280C19-L280C26 and it looks like it? If so, I could parse it out. I am guessing the code they have [here](https://github.com/thrnz/docker-wireguard-pia/blob/5c6fd5dc6dcd204c6a6a7c56e5637928446ede0b/extra/pf.sh#L188-L200) doesn't actually work, same as Gluetun. So possibly we cannot auto-magically determine the API IP address 🤔 Alternatively, would you be ok having a new option `PORT_FORWARDING_API_IP` which you can set to `10.9.128.1` for example?

It seems that at least from the wg0 config files there seems to be a #pf api ip.
We can definitely at least try adding the variable to tests if at least that finally fixes the issue.

**Comment by qdm12** [comment]
Is there a consistent difference between the `pf api ip` described in the Wireguard configuration file and the gateway IP you find using `docker exec gluetun traceroute -4 -m 1 -i tun0 privateinternetaccess.com`?

How about when running `docker exec gluetun ip route show table all`, do you get anywhere the same API IP as the one in the wireguard config file? Or something looking similar? For now Gluetun uses routes to find the gateway, maybe it's the wrong logic and it should look elsewhere. That way it would be automated, and not dependent on the `# pf api ip` comment, which could change in the future possibly.

**Comment by xtinct101** [comment]
thornz wg0 = #pf api ip: 10.3.128.1

executing `docker exec gluetun traceroute -4 -m 1 -i tun0 privateinternetaccess.com` returns: 
`10.3.128.1`

executing `docker exec gluetun ip route show table all` returns:
```default dev tun0 table 51820 
192.168.90.0/24 via 192.168.90.1 dev eth0 table 199 
default via 192.168.90.1 dev eth0 table 200 
default via 192.168.90.1 dev eth0 
192.168.90.0/24 dev eth0 proto kernel scope link src 192.168.90.12 
local 10.3.249.20 dev tun0 table local proto kernel scope host src 10.3.249.20 
local 127.0.0.0/8 dev lo table local proto kernel scope host src 127.0.0.1 
local 127.0.0.1 dev lo table local proto kernel scope host src 127.0.0.1 
broadcast 127.255.255.255 dev lo table local proto kernel scope link src 127.0.0.1 
local 192.168.90.12 dev eth0 table local proto kernel scope host src 192.168.90.12 
broadcast 192.168.90.255 dev eth0 table local proto kernel scope link src 192.168.90.12```

**Comment by qdm12** [comment]
@xtinct101 a few questions:

1. The pia-thornz returns the wrong API IP address `10.4.128.1` using traceroute, correct (at least compared to the wireguard config file)? Or is this one IP address `10.4.128.1` working as well?
2. I'm thinking, is the API IP address consistently [2 parts from assigned IP] + `128.1`? For example from `local 10.3.249.20 dev tun0 table local proto kernel scope host src 10.3.249.20`, you take `10.3` and add `128.1` and you have your API IP address 🤔 Could you check with other servers if this seems consistent? A bit hacky, but if it does the job 🤷 Obviously, this depends on question 1. as well!

@macdis the problem is right now Gluetun cannot do networking before the tunnel is up, and registering a wireguard key after wireguard is setup sounds quite strange. Is there any way to fetch that `server_vip` without registering a wireguard key? I opened https://github.com/pia-foss/manual-connections/issues/190 regarding this.

**Comment by dreary-ennui** [comment]
>     2. I'm thinking, is the API IP address consistently [2 parts from assigned IP] + `128.1`? [...] Could you check with 1 or 2 other servers if this seems consistent? 

I know I'm not the person you're asking, but this does seem to be correct with several servers I've tried and looked at the wg0.conf after a connection is established.

**Comment by qdm12** [comment]
Can you try with image tag `:pr-2420`? I opened #2420 which computes the API IP address that way. If it works, can you also try using OpenVPN (using `VPN_SERVICE_PROVIDER=private internet access`) to check if the gateway computation only works for Wireguard or not?

**Comment by xtinct101** [comment]
Yep, that seemed to do it!!!
```
gluetun  | 2024-08-16T13:58:20.972394445Z 2024-08-16T13:58:20Z INFO [port forwarding] starting
gluetun  | 2024-08-16T13:58:21.349513541Z 2024-08-16T13:58:21Z INFO [port forwarding] Port forwarded data expires in 62 days
gluetun  | 2024-08-16T13:58:21.363755540Z 2024-08-16T13:58:21Z INFO [port forwarding] port forwarded is 45263
gluetun  | 2024-08-16T13:58:21.363804820Z 2024-08-16T13:58:21Z INFO [firewall] setting allowed input port 45263 through interface tun0...
gluetun  | 2024-08-16T13:58:21.363813214Z 2024-08-16T13:58:21Z DEBUG [firewall] iptables --append INPUT -i tun0 -p tcp -m tcp --dport 45263 -j ACCEPT
gluetun  | 2024-08-16T13:58:21.366622356Z 2024-08-16T13:58:21Z DEBUG [firewall] ip6tables --append INPUT -i tun0 -p tcp -m tcp --dport 45263 -j ACCEPT
gluetun  | 2024-08-16T13:58:21.369118405Z 2024-08-16T13:58:21Z DEBUG [firewall] iptables --append INPUT -i tun0 -p udp -m udp --dport 45263 -j ACCEPT
gluetun  | 2024-08-16T13:58:21.371871656Z 2024-08-16T13:58:21Z DEBUG [firewall] ip6tables --append INPUT -i tun0 -p udp -m udp --dport 45263 -j ACCEPT
gluetun  | 2024-08-16T13:58:21.374546590Z 2024-08-16T13:58:21Z INFO [port forwarding] writing port file /gluetun/port.txt
```

**Comment by xtinct101** [comment]
while it now seems likes it working'ish, the vpn is restarting every x-sec
```
gluetun  | 2024-08-16T13:59:32.408626619Z 2024-08-16T13:59:32Z INFO [healthcheck] program has been unhealthy for 6s: restarting VPN
gluetun  | 2024-08-16T13:59:32.408699943Z 2024-08-16T13:59:32Z INFO [healthcheck] 👉 See https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md
gluetun  | 2024-08-16T13:59:32.408715408Z 2024-08-16T13:59:32Z INFO [healthcheck] DO NOT OPEN AN ISSUE UNLESS YOU READ AND TRIED EACH POSSIBLE SOLUTION
gluetun  | 2024-08-16T13:59:32.408724737Z 2024-08-16T13:59:32Z INFO [vpn] stopping
gluetun  | 2024-08-16T13:59:32.408784153Z 2024-08-16T13:59:32Z INFO [port forwarding] stopping
gluetun  | 2024-08-16T13:59:32.408835023Z 2024-08-16T13:59:32Z INFO [firewall] removing allowed port 45263...
gluetun  | 2024-08-16T13:59:32.408848913Z 2024-08-16T13:59:32Z DEBUG [firewall] iptables --delete INPUT -i tun0 -p tcp -m tcp --dport 45263 -j ACCEPT
gluetun  | 2024-08-16T13:59:32.412438643Z 2024-08-16T13:59:32Z DEBUG [firewall] ip6tables --delete INPUT -i tun0 -p tcp -m tcp --dport 45263 -j ACCEPT
gluetun  | 2024-08-16T13:59:32.444086252Z 2024-08-16T13:59:32Z DEBUG [firewall] iptables --delete INPUT -i tun0 -p udp -m udp --dport 45263 -j ACCEPT
gluetun  | 2024-08-16T13:59:32.472107065Z 2024-08-16T13:59:32Z DEBUG [firewall] ip6tables --delete INPUT -i tun0 -p udp -m udp --dport 45263 -j ACCEPT
gluetun  | 2024-08-16T13:59:32.496158556Z 2024-08-16T13:59:32Z INFO [port forwarding] removing port file /gluetun/port.txt
```

**Comment by qdm12** [comment]
@xtinct101 Does port forwarding work with **OpenVPN**, using the native PIA openvpn+Port forwarding integration?

All this 'native support' for PIA Wireguard+Port forwarding will come later, once Gluetun can do (very restriced) networking when the VPN tunnel is not up, to generate that Wireguard configuration file as you mentioned.

I need to update the Wiki though, so what you need (let me know if I forgot something):

- Generate a Wireguard configuration file for a server which supports VPN port forwarding (any link to a list?)
- `VPN_PORT_FORWARDING=on`
- `VPN_PORT_FORWARDING_PROVIDER=private internet access`
- `SERVER_NAMES` must be set to the server name for TLS validation when communicating with their API, for example `panama408`

**Comment by xtinct101** [comment]
@qdm12 just verified both wireguard and openvpn work with port forwarding.

also require
- VPN_PORT_FORWARDING_USERNAME="p5100741"
- VPN_PORT_FORWARDING_PASSWORD="C9JVHpdprs"

This is the only list I'm aware of.
https://[serverlist.piaservers.net/vpninfo/servers/v6](https://serverlist.piaservers.net/vpninfo/servers/v6)

**Comment by JoooostB** [comment]
@xtinct101 Please note that your password got sent to everyone who subscribed to this issue and is still visible in history, you should really change it ASAP!

@qdm12 I tested Wireguard here as well, which works perfectly if `SERVER_NAMES` only contains one value. When another name is added, separated by a comma, it won't go through and fails on certificate validation.

**Comment by xtinct101** [comment]
@JoooostB yes I know I hit send before erasing it. I've already changed it. Thanks regardless!

**Comment by xtinct101** [comment]
@qdm12 just verified both wireguard and openvpn work with port forwarding.

also require

VPN_PORT_FORWARDING_USERNAME=""
VPN_PORT_FORWARDING_PASSWORD=""
This is the only list I'm aware of.
https://[serverlist.piaservers.net/vpninfo/servers/v6](https://serverlist.piaservers.net/vpninfo/servers/v6)

**Comment by qdm12** [comment]
The PR is merged (latest image), and the wiki's PIA page is updated 👍 
Thank you all for your help! 💯

**Comment by OfficePop** [comment]
I just caught up on all this-is there a way to obtain the server name needed with pia-wf-config? That's what i've been using to generate a WG config with gluetun.

**Comment by shanew1694** [comment]
So I had Wireguard with port forwarding working some time ago, but I guess the server I was using was depreciated and therefore it stopped working. It was a huge hassle to get it back working.

Here is what I did:
1. Find a server that's currently in the server.json file in the region you want (uk_2)
2. Make a note of the IP and the SERVER_NAME (london441)
3. Spam the crap out of "pia-wg-config uk_2"  until you get the server ip you need.

There seem to be way more servers that you can find using pia-wg-config than there are in server.json but it seems you can only use those specific servers, otherwise, you get timeout errors etc.

**Comment by xtinct101** [comment]
yes this recently happened to me, was working perfectly well for the last few months, then server changed. Getting it back up and running was a mission as stated by @shanew1694 

> So I had Wireguard with port forwarding working some time ago, but I guess the server I was using was depreciated and therefore it stopped working. It was a huge hassle to get it back working.
> 
> Here is what I did:
> 
> 1. Find a server that's currently in the server.json file in the region you want (uk_2)
> 2. Make a note of the IP and the SERVER_NAME (london441)
> 3. Spam the crap out of "pia-wg-config uk_2"  until you get the server ip you need.
> 
> There seem to be way more servers that you can find using pia-wg-config than there are in server.json but it seems you can only use those specific servers, otherwise, you get timeout errors etc.
