### ISSUE TITLE
Bug: Privado manual Server Update doesnt work

### ISSUE THREAD

**Issue by alfredneumann** [qdm12/gluetun#2424]
### Is this urgent?

No

### Host OS

unraid 6.12.11

### CPU arch

x86_64

### VPN service provider

Privado

### What are you using to run the container

Unraid

### What is the version of Gluetun

Running version latest built on 2024-08-17T18:15:23.123Z (commit bc55c25)

### What's the problem 🤔

Manual Update for VPN Server List with Privado VPN doesn't work.

### Share your logs (at least 10 lines)

```plain text
docker run --rm -v /mnt/virtpool/docker/appdata/gluetun qmcgaw/gluetun update -enduser -providers privado
2024-08-18T05:49:14Z INFO creating /gluetun/servers.json with 20615 hardcoded servers
2024-08-18T05:49:14Z INFO updating Privado servers...
2024-08-18T05:49:15Z WARN note: if running the update manually, you can use the flag -minratio to allow the update to succeed with less servers found
2024-08-18T05:49:15Z ERROR updating server information: getting servers: not enough servers found: 156 and expected at least 234
2024-08-18T05:49:15Z INFO Shutdown successful


docker run --rm -v /mnt/virtpool/docker/appdata/gluetun qmcgaw/gluetun update -enduser -providers privado -minratio 0.1
2024-08-18T05:43:49Z INFO creating /gluetun/servers.json with 20615 hardcoded servers
2024-08-18T05:43:49Z INFO updating Privado servers...
2024-08-18T05:43:50Z ERROR updating server information: getting servers: decoding response: gzip: invalid header
2024-08-18T05:43:50Z INFO Shutdown successful
```

**Comment by qdm12** [comment]
> ERROR updating server information: getting servers: not enough servers found: 156 and expected at least 234

Indeed, I got the same error, this happens 🤷 I guess Privado just removed a lot of servers suddenly.
Using `-minratio 0.1` solves it as you did. I pushed the servers update to the latest image since that error can be a bit troublesome, so it's worth updating servers built-in I guess 😉 

> ERROR updating server information: getting servers: decoding response: gzip: invalid header

I'm not getting this. Can you try again? It might had been a misconfiguration on Privado's website 🤔 
For more details, sending an HTTP GET to https://privadovpn.com/apps/ovpn_configs.zip gives back a response with a `Content-Encoding` HTTP header with value `gzip`, although the zip file is not gzip-ed by Privado's http server, hence the error `decoding response: gzip: invalid header`

**Comment by alfredneumann** [comment]
Hello,
Thank you very much for your work on this. I tried it again today and didn't get an error message but the list was still not updated.

In the downloaded ovpn_configs.zip as example Netherlands/Amsterdam Server starting with ams-025
akl-012.tcp-scramble.ovpn
ams-025.default.ovpn
ams-025.tcp-scramble.ovpn
ams-026.default.ovpn
ams-026.tcp-scramble.ovpn
ams-027.default.ovpn
ams-027.tcp-scramble.ovpn
ams-028.default.ovpn
ams-028.tcp-scramble.ovpn
ams-029.default.ovpn
ams-029.tcp-scramble.ovpn
ams-030.default.ovpn
ams-030.tcp-scramble.ovpn
ams-031.default.ovpn
ams-031.tcp-scramble.ovpn
ams-032.default.ovpn
ams-032.tcp-scramble.ovpn
ams-033.default.ovpn
ams-033.tcp-scramble.ovpn
ams-034.default.ovpn
ams-034.tcp-scramble.ovpn
ams-035.default.ovpn
ams-035.tcp-scramble.ovpn
ams-036.default.ovpn
ams-036.tcp-scramble.ovpn
ams-037.default.ovpn
ams-037.tcp-scramble.ovpn
arn-006.default.ovpn

**But the servers in my updatete list start with ams-001, and this servers are not reachable anymore.**

docker run --rm -v /mnt/virtpool/docker/appdata/gluetun qmcgaw/gluetun:latest update -enduser -providers privado -minratio 0.1
2024-08-19T05:36:57Z INFO creating /gluetun/servers.json with 20615 hardcoded servers
2024-08-19T05:36:57Z INFO updating Privado servers...
 
docker run --rm -v /mnt/virtpool/docker/appdata/gluetun qmcgaw/gluetun format-servers -privado
| Country | Region | City | Hostname |
| --- | --- | --- | --- |
....
| Malaysia | Kuala Lumpur | Kuala Lumpur | `kul-004.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `ams-001.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `ams-002.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `ams-003.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `ams-004.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `ams-005.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `ams-006.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `ams-007.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `ams-008.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `lhr-060.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `lhr-061.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `lhr-062.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `lhr-063.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `rkv-006.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `rkv-007.vpn.privado.io` |
| Netherlands | North Holland | Burgerveen | `ams-009.vpn.privado.io` |
| Netherlands | North Holland | Haarlem | `lhr-064.vpn.privado.io` |
| Netherlands | North Holland | Haarlem | `lhr-065.vpn.privado.io` |
| New Zealand | Auckland | Auckland | `akl-006.vpn.privado.io` |
....

Standardserver:  dns.google
Address:  8.8.8.8

> ams-001.vpn.privado.io
Server:  dns.google
Address:  8.8.8.8

*** ams-001.vpn.privado.io wurde von dns.google nicht gefunden: Non-existent domain.

**Comment by qdm12** [comment]
Try pulling the latest image? When running the latest image I get:

```
docker run --rm qmcgaw/gluetun format-servers -privado | grep Amsterdam
| Netherlands | North Holland | Amsterdam | `ams-025.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `ams-026.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `ams-027.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `ams-028.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `ams-029.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `ams-030.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `ams-031.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `ams-032.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `ams-033.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `ams-034.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `ams-035.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `ams-036.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `ams-037.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `beg-003.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `beg-004.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `bom-005.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `bom-006.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `bom-007.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `bom-008.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `bru-005.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `bru-006.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `cph-005.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `cph-006.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `dub-005.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `dub-006.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `hel-003.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `hel-004.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `jnb-008.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `jnb-009.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `jrs-003.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `jrs-004.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `lhr-060.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `lhr-061.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `lhr-062.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `lhr-063.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `lhr-064.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `lhr-065.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `mad-005.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `mad-006.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `man-009.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `man-010.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `prg-003.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `prg-004.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `rkv-007.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `svo-005.vpn.privado.io` |
| Netherlands | North Holland | Amsterdam | `svo-006.vpn.privado.io` |
```

So clearly `ams-001.vpn.privado.io` is not there, and it reflects the openvpn zip file content.

**Comment by qdm12** [comment]
The problem is `-v /mnt/virtpool/docker/appdata/gluetun`, you are missing the other part of the bind mount. It should be `-v /mnt/virtpool/docker/appdata/gluetun:/gluetun` to persist servers data. So when you update, the data is lost after the program exits, because it's not persisted. Closing this assuming this is just a configuration problem on your end.
