### ISSUE TITLE
Help: Port forwarding cannot obtain token due to router (I think)

### ISSUE THREAD

**Issue by Suddow** [qdm12/gluetun#292]
**TLDR**: *Describe your issue in a one liner here*
Getting the following error:
port forwarding: cannot obtain token: Get "https://[username]:***@10.0.0.1/authv3/generateToken": x509: certificate is valid for myrouter.io, not toronto405

It seems to be related in some way to my router, but I don't know how to fix it.  If I go to the above url it just leads to my router login page, though it looks slightly different (less formatting on the page, login doesn't work, etc)

Use case will be to forward deluge torrents through the vpn (and figure out a way to still be able to connect with the windows GUI client on LAN)

1. Is this urgent?

    - [ ] Yes
    - [x] No

2. What VPN service provider are you using?

    - [x] PIA
    - [ ] Mullvad
    - [ ] Windscribe
    - [ ] Surfshark
    - [ ] Cyberghost

3. What's the version of the program?

 Running version unknown built on an unknown date (commit unknown)

2020-11-07T15:16:59.711-0400	INFO	OpenVPN version: 2.4.9
2020-11-07T15:16:59.777-0400	INFO	Unbound version: 1.10.1
2020-11-07T15:16:59.802-0400	INFO	IPtables version: v1.8.4

4. What are you using to run the container?

    - [ ] Docker run
    - [x] Docker Compose
    - [ ] Kubernetes
    - [ ] Docker stack
    - [ ] Docker swarm
    - [ ] Podman
    - [ ] Other:

5. Extra information

Logs:

```log
=========================================,
================ Gluetun ================,
=========================================,
==== A mix of OpenVPN, DNS over TLS, ====,
======= Shadowsocks and HTTP proxy ======,
========= all glued up with Go ==========,
=========================================,
=========== For tunneling to ============,
======== your favorite VPN server =======,
=========================================,
=== Made with ❤️  by github.com/qdm12 ====,
=========================================,
,
Running version unknown built on an unknown date (commit unknown),
,
📣  Port forwarding is working for PIA v4 servers,
,
🔧  Need help? https://github.com/qdm12/gluetun/issues/new,
💻  Email? quentin.mcgaw@gmail.com,
☕  Slack? Join from the Slack button on Github,
💸  Help me? https://github.com/sponsors/qdm12,
2020-11-07T15:16:59.711-0400	INFO	OpenVPN version: 2.4.9,
2020-11-07T15:16:59.777-0400	INFO	Unbound version: 1.10.1,
2020-11-07T15:16:59.802-0400	INFO	IPtables version: v1.8.4,
2020-11-07T15:16:59.802-0400	WARN	You are using the old environment variable EXTRA_SUBNETS, please consider changing it to FIREWALL_OUTBOUND_SUBNETS,
2020-11-07T15:16:59.803-0400	INFO	Settings summary below:,
OpenVPN settings:,
|--User: [redacted],
|--Password: [redacted],
|--Verbosity level: 1,
|--Run as root: no,
|--Private Internet Access settings:,
 |--Network protocol: udp,
 |--Regions: ca toronto,
 |--Encryption preset: strong,
 |--Port forwarding: on, saved in /tmp/gluetun/forwarded_port,
System settings:,
|--User ID: 1000,
|--Group ID: 1000,
|--Timezone: america/toronto,
|--IP Status filepath: /tmp/gluetun/ip,
DNS over TLS settings:,
 |--DNS over TLS provider:,
  |--cloudflare,
 |--Caching: enabled,
 |--Block malicious: enabled,
 |--Block surveillance: disabled,
 |--Block ads: disabled,
 |--Allowed hostnames:,
  |--,
 |--Private addresses:,
  |--127.0.0.1/8,
  |--10.0.0.0/8,
  |--172.16.0.0/12,
  |--192.168.0.0/16,
  |--169.254.0.0/16,
  |--::1/128,
  |--fc00::/7,
  |--fe80::/10,
  |--::ffff:0:0/96,
 |--Verbosity level: 1/5,
 |--Verbosity details level: 0/4,
 |--Validation log level: 0/2,
 |--IPv6 resolution: disabled,
 |--Update: every 24h0m0s,
 |--Keep nameserver (disabled blocking): no,
Firewall settings:,
 |--VPN input ports: ,
 |--Input ports: ,
 |--Outbound subnets: 10.0.0.0/24,
HTTP Proxy settings: disabled,
ShadowSocks settings:,
 |--Password: [redacted],
 |--Log: enabled,
 |--Port: 8388,
 |--Method: chacha20-ietf-poly1305,
HTTP Control server:,
 |--Listening port: 8000,
 |--Logging: true,
Public IP check period: 12h0m0s,
Version information: enabled,
Updater: disabled,
,
2020-11-07T15:16:59.860-0400	INFO	storage: Merging by most recent 6556 hardcoded servers and 6556 servers read from /gluetun/servers.json,
2020-11-07T15:16:59.903-0400	INFO	routing: default route found: interface eth0, gateway 172.17.0.1,
2020-11-07T15:16:59.903-0400	INFO	routing: local subnet found: 172.17.0.0/16,
2020-11-07T15:16:59.904-0400	INFO	routing: default route found: interface eth0, gateway 172.17.0.1,
2020-11-07T15:16:59.904-0400	INFO	routing: adding route for 0.0.0.0/0,
2020-11-07T15:16:59.904-0400	INFO	firewall: firewall disabled, only updating allowed subnets internal list,
2020-11-07T15:16:59.904-0400	INFO	routing: default route found: interface eth0, gateway 172.17.0.1,
2020-11-07T15:16:59.904-0400	INFO	routing: adding route for 10.0.0.0/24,
2020-11-07T15:16:59.904-0400	INFO	openvpn configurator: checking for device /dev/net/tun,
2020-11-07T15:16:59.904-0400	WARN	TUN device is not available: open /dev/net/tun: no such file or directory,
2020-11-07T15:16:59.904-0400	INFO	openvpn configurator: creating /dev/net/tun,
2020-11-07T15:16:59.904-0400	INFO	firewall: enabling...,
2020-11-07T15:16:59.955-0400	INFO	firewall: enabled successfully,
2020-11-07T15:16:59.956-0400	INFO	Launching standard output merger,
2020-11-07T15:16:59.956-0400	INFO	dns over tls: falling back on plaintext DNS at address 1.1.1.1,
2020-11-07T15:16:59.957-0400	INFO	dns configurator: using DNS address 1.1.1.1 internally,
2020-11-07T15:16:59.957-0400	INFO	dns configurator: using DNS address 1.1.1.1 system wide,
2020-11-07T15:16:59.957-0400	INFO	healthcheck: listening on 127.0.0.1:9999,
2020-11-07T15:16:59.958-0400	INFO	http server: listening on 0.0.0.0:8000,
2020-11-07T15:16:59.959-0400	INFO	firewall: setting VPN connection through firewall...,
2020-11-07T15:16:59.961-0400	INFO	shadowsocks: listening TCP on 0.0.0.0:8388,
2020-11-07T15:16:59.961-0400	INFO	shadowsocks: listening UDP on 0.0.0.0:8388,
2020-11-07T15:16:59.973-0400	INFO	openvpn configurator: starting openvpn,
2020-11-07T15:16:59.975-0400	INFO	openvpn: OpenVPN 2.4.9 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020,
2020-11-07T15:16:59.975-0400	INFO	openvpn: library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10,
2020-11-07T15:17:00.000-0400	INFO	openvpn: CRL: loaded 1 CRLs from file [[INLINE]],
2020-11-07T15:17:00.000-0400	INFO	openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]172.83.47.250:1197,
2020-11-07T15:17:00.000-0400	INFO	openvpn: UDP link local: (not bound),
2020-11-07T15:17:00.000-0400	INFO	openvpn: UDP link remote: [AF_INET]172.83.47.250:1197,
2020-11-07T15:17:00.416-0400	WARN	openvpn: 'link-mtu' is used inconsistently, local='link-mtu 1570', remote='link-mtu 1542',
2020-11-07T15:17:00.417-0400	WARN	openvpn: 'cipher' is used inconsistently, local='cipher AES-256-CBC', remote='cipher BF-CBC',
2020-11-07T15:17:00.417-0400	WARN	openvpn: 'auth' is used inconsistently, local='auth SHA256', remote='auth SHA1',
2020-11-07T15:17:00.417-0400	WARN	openvpn: 'keysize' is used inconsistently, local='keysize 256', remote='keysize 128',
2020-11-07T15:17:00.417-0400	INFO	openvpn: [toronto405] Peer Connection Initiated with [AF_INET]172.83.47.250:1197,
2020-11-07T15:17:01.681-0400	INFO	openvpn: TUN/TAP device tun0 opened,
2020-11-07T15:17:01.681-0400	INFO	openvpn: /sbin/ip link set dev tun0 up mtu 1500,
2020-11-07T15:17:01.783-0400	INFO	openvpn: /sbin/ip addr add dev tun0 10.51.110.3/24 broadcast 10.51.110.255,
2020-11-07T15:17:01.787-0400	INFO	openvpn: UID set to nonrootuser,
2020-11-07T15:17:01.788-0400	INFO	openvpn: Initialization Sequence Completed,
2020-11-07T15:17:01.788-0400	INFO	dns configurator: downloading root hints from https://raw.githubusercontent.com/qdm12/files/master/named.root.updated,
2020-11-07T15:17:01.788-0400	INFO	VPN routing IP address: 172.83.47.250,
2020-11-07T15:17:01.788-0400	INFO	VPN gateway IP address: 10.51.110.1,
2020-11-07T15:17:01.807-0400	ERROR	port forwarding: cannot obtain token: Get "https://[username]:***@10.0.0.1/authv3/generateToken": x509: certificate is valid for myrouter.io, not toronto405,
2020-11-07T15:17:01.807-0400	INFO	port forwarding: Trying again in 10s,
2020-11-07T15:17:02.458-0400	INFO	dns configurator: downloading root key from https://raw.githubusercontent.com/qdm12/files/master/root.key.updated,
2020-11-07T15:17:02.491-0400	INFO	dns configurator: generating Unbound configuration,
2020-11-07T15:17:02.782-0400	INFO	dns configurator: 63525 hostnames blocked overall,
2020-11-07T15:17:02.782-0400	INFO	dns configurator: 2695 IP addresses blocked overall,
2020-11-07T15:17:02.921-0400	INFO	dns configurator: starting unbound,
2020-11-07T15:17:02.922-0400	INFO	dns configurator: using DNS address 127.0.0.1 internally,
2020-11-07T15:17:02.922-0400	INFO	dns configurator: using DNS address 127.0.0.1 system wide,
2020-11-07T15:17:03.289-0400	INFO	unbound: init module 0: validator,
2020-11-07T15:17:03.289-0400	INFO	unbound: init module 1: iterator,
2020-11-07T15:17:03.304-0400	INFO	unbound: start of service (unbound 1.10.1).,
2020-11-07T15:17:03.433-0400	INFO	unbound: generate keytag query _ta-4a5c-4f66. NULL IN,
2020-11-07T15:17:03.954-0400	INFO	dns over tls: DNS over TLS is ready,
2020-11-07T15:17:04.309-0400	INFO	There is a new release v3.6.0 (HTTP proxy in Go) created 2 days ago,
2020-11-07T15:17:04.670-0400	INFO	ip getter: Public IP address is 172.83.47.250,
2020-11-07T15:17:11.835-0400	ERROR	port forwarding: cannot obtain token: Get "https://[username]:***@10.0.0.1/authv3/generateToken": x509: certificate is valid for myrouter.io, not toronto405,
2020-11-07T15:17:11.835-0400	INFO	port forwarding: Trying again in 10s,
2020-11-07T15:17:21.859-0400	ERROR	port forwarding: cannot obtain token: Get "https://[username]:***@10.0.0.1/authv3/generateToken": x509: certificate is valid for myrouter.io, not toronto405,
2020-11-07T15:17:21.859-0400	INFO	port forwarding: Trying again in 10s,
2020-11-07T15:17:31.886-0400	ERROR	port forwarding: cannot obtain token: Get "https://[username]:***@10.0.0.1/authv3/generateToken": x509: certificate is valid for myrouter.io, not toronto405,
2020-11-07T15:17:31.886-0400	INFO	port forwarding: Trying again in 10s,
2020-11-07T15:17:41.914-0400	ERROR	port forwarding: cannot obtain token: Get "https://[username]:***@10.0.0.1/authv3/generateToken": x509: certificate is valid for myrouter.io, not toronto405,
2020-11-07T15:17:41.914-0400	INFO	port forwarding: Trying again in 10s,
2020-11-07T15:17:51.938-0400	ERROR	port forwarding: cannot obtain token: Get "https://[username]:***@10.0.0.1/authv3/generateToken": x509: certificate is valid for myrouter.io, not toronto405,
2020-11-07T15:17:51.938-0400	INFO	port forwarding: Trying again in 10s,
2020-11-07T15:18:01.964-0400	ERROR	port forwarding: cannot obtain token: Get "https://[username]:***@10.0.0.1/authv3/generateToken": x509: certificate is valid for myrouter.io, not toronto405,
2020-11-07T15:18:01.964-0400	INFO	port forwarding: Trying again in 10s,
2020-11-07T15:18:11.994-0400	ERROR	port forwarding: cannot obtain token: Get "https://[username]:***@10.0.0.1/authv3/generateToken": x509: certificate is valid for myrouter.io, not toronto405,
2020-11-07T15:18:11.994-0400	INFO	port forwarding: Trying again in 10s,
2020-11-07T15:18:22.024-0400	ERROR	port forwarding: cannot obtain token: Get "https://[username]:***@10.0.0.1/authv3/generateToken": x509: certificate is valid for myrouter.io, not toronto405,
2020-11-07T15:18:22.025-0400	INFO	port forwarding: Trying again in 10s,
2020-11-07T15:18:32.052-0400	ERROR	port forwarding: cannot obtain token: Get "https://[username]:***@10.0.0.1/authv3/generateToken": x509: certificate is valid for myrouter.io, not toronto405,
2020-11-07T15:18:32.052-0400	INFO	port forwarding: Trying again in 10s,
2020-11-07T15:18:42.078-0400	ERROR	port forwarding: cannot obtain token: Get "https://[username]:***@10.0.0.1/authv3/generateToken": x509: certificate is valid for myrouter.io, not toronto405,
2020-11-07T15:18:42.078-0400	INFO	port forwarding: Trying again in 10s,
2020-11-07T15:18:52.108-0400	ERROR	port forwarding: cannot obtain token: Get "https://[username]:***@10.0.0.1/authv3/generateToken": x509: certificate is valid for myrouter.io, not toronto405,
2020-11-07T15:18:52.108-0400	INFO	port forwarding: Trying again in 10s,
2020-11-07T15:19:02.186-0400	ERROR	port forwarding: cannot obtain token: Get "https://[username]:***@10.0.0.1/authv3/generateToken": x509: certificate is valid for myrouter.io, not toronto405,
2020-11-07T15:19:02.186-0400	INFO	port forwarding: Trying again in 10s,
2020-11-07T15:19:12.217-0400	ERROR	port forwarding: cannot obtain token: Get "https://[username]:***@10.0.0.1/authv3/generateToken": x509: certificate is valid for myrouter.io, not toronto405,
2020-11-07T15:19:12.217-0400	INFO	port forwarding: Trying again in 10s,
2020-11-07T15:19:22.245-0400	ERROR	port forwarding: cannot obtain token: Get "https://[username]:***@10.0.0.1/authv3/generateToken": x509: certificate is valid for myrouter.io, not toronto405,
2020-11-07T15:19:22.245-0400	INFO	port forwarding: Trying again in 10s,
2020-11-07T15:19:32.274-0400	ERROR	port forwarding: cannot obtain token: Get "https://[username]:***@10.0.0.1/authv3/generateToken": x509: certificate is valid for myrouter.io, not toronto405,
2020-11-07T15:19:32.274-0400	INFO	port forwarding: Trying again in 10s,
2020-11-07T15:19:42.304-0400	ERROR	port forwarding: cannot obtain token: Get "https://[username]:***@10.0.0.1/authv3/generateToken": x509: certificate is valid for myrouter.io, not toronto405,
2020-11-07T15:19:42.304-0400	INFO	port forwarding: Trying again in 10s,
2020-11-07T15:19:52.336-0400	ERROR	port forwarding: cannot obtain token: Get "https://[username]:***@10.0.0.1/authv3/generateToken": x509: certificate is valid for myrouter.io, not toronto405,
2020-11-07T15:19:52.336-0400	INFO	port forwarding: Trying again in 10s,
2020-11-07T15:20:02.362-0400	ERROR	port forwarding: cannot obtain token: Get "https://[username]:***@10.0.0.1/authv3/generateToken": x509: certificate is valid for myrouter.io, not toronto405,
2020-11-07T15:20:02.362-0400	INFO	port forwarding: Trying again in 10s,
2020-11-07T15:20:12.390-0400	ERROR	port forwarding: cannot obtain token: Get "https://[username]:***@10.0.0.1/authv3/generateToken": x509: certificate is valid for myrouter.io, not toronto405,
2020-11-07T15:20:12.390-0400	INFO	port forwarding: Trying again in 10s,
2020-11-07T15:20:22.417-0400	ERROR	port forwarding: cannot obtain token: Get "https://[username]:***@10.0.0.1/authv3/generateToken": x509: certificate is valid for myrouter.io, not toronto405,
2020-11-07T15:20:22.417-0400	INFO	port forwarding: Trying again in 10s,
2020-11-07T15:20:32.445-0400	ERROR	port forwarding: cannot obtain token: Get "https://[username]:***@10.0.0.1/authv3/generateToken": x509: certificate is valid for myrouter.io, not toronto405,
2020-11-07T15:20:32.445-0400	INFO	port forwarding: Trying again in 10s,
2020-11-07T15:20:42.472-0400	ERROR	port forwarding: cannot obtain token: Get "https://[username]:***@10.0.0.1/authv3/generateToken": x509: certificate is valid for myrouter.io, not toronto405,
2020-11-07T15:20:42.472-0400	INFO	port forwarding: Trying again in 10s,
2020-11-07T15:20:52.500-0400	ERROR	port forwarding: cannot obtain token: Get "https://[username]:***@10.0.0.1/authv3/generateToken": x509: certificate is valid for myrouter.io, not toronto405,
2020-11-07T15:20:52.500-0400	INFO	port forwarding: Trying again in 10s,
2020-11-07T15:21:02.531-0400	ERROR	port forwarding: cannot obtain token: Get "https://[username]:***@10.0.0.1/authv3/generateToken": x509: certificate is valid for myrouter.io, not toronto405,
2020-11-07T15:21:02.531-0400	INFO	port forwarding: Trying again in 10s,
```

Configuration file:

```yml
version: "3.7"
services:
  gluetun:
    image: qmcgaw/private-internet-access
    network_mode: bridge        # Required
    cap_add:
      - NET_ADMIN               # Required
    environment:                # 
    - VPNSP=private internet access
    - TZ=America/Toronto
    - USER=
    - PASSWORD=
    - REGION=CA Toronto
    - PORT_FORWARDING=on
    - EXTRA_SUBNETS=10.0.0.0/24
    - SHADOWSOCKS=on
    - SHADOWSOCKS_PASSWORD=password
    - SHADOWSOCKS_LOG=on
    volumes:
      - /volume1/docker/gluetun_pia_vpn:/gluetun
      - /volume1/docker/gluetun_forwarded_port:/tmp/gluetun/forwarded_port
    ports:
      - 8112:8112     #deluge
      - 58846:58846   #deluge daemon port
      - 58946:58946   #deluge
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8100:8000/tcp # Built-in HTTP control server
    restart: always
```

Host OS:
Synology DSM

**Comment by qdm12** [comment]
Thanks for reporting the issue!

That's definitely interesting. So your router is at `10.0.0.1` with I assume an HTTPS self signed certificate for `myrouter.io` right?

I don't want to point fingers, but I think PIA decided to use `10.0.0.1` as the server local IP address to use as this wouldn't conflict with most users network 😅 Let me know. I'll investigate how to route that request through the tunnel only and not through your local LAN.

**Comment by Suddow** [comment]
Correct, 10.0.0.1 is the router address. 

As for the https certificate, I don't actually know anything about that.  There doesn't appear to be any certificate when I'm on that page in the browser, but I couldn't tell you if that means anything.

**Comment by Suddow** [comment]
I think you were right.  I have reconfigured my gateway (and all my other services... that was fun), here's my new log, can you confirm this indicates it's working?  It seems to be for me.

```
=========================================,
================ Gluetun ================,
=========================================,
==== A mix of OpenVPN, DNS over TLS, ====,
======= Shadowsocks and HTTP proxy ======,
========= all glued up with Go ==========,
=========================================,
=========== For tunneling to ============,
======== your favorite VPN server =======,
=========================================,
=== Made with ❤️  by github.com/qdm12 ====,
=========================================,
,
Running version unknown built on an unknown date (commit unknown),
,
📣  Port forwarding is working for PIA v4 servers,
,
🔧  Need help? https://github.com/qdm12/gluetun/issues/new,
💻  Email? quentin.mcgaw@gmail.com,
☕  Slack? Join from the Slack button on Github,
💸  Help me? https://github.com/sponsors/qdm12,
2020-11-08T13:12:54.335-0400	INFO	OpenVPN version: 2.4.9,
2020-11-08T13:12:54.427-0400	INFO	Unbound version: 1.10.1,
2020-11-08T13:12:54.661-0400	INFO	IPtables version: v1.8.4,
2020-11-08T13:12:54.661-0400	INFO	Settings summary below:,
OpenVPN settings:,
|--User: [redacted],
|--Password: [redacted],
|--Verbosity level: 1,
|--Run as root: no,
|--Private Internet Access settings:,
 |--Network protocol: udp,
 |--Regions: ca toronto,
 |--Encryption preset: strong,
 |--Port forwarding: on, saved in /tmp/gluetun/forwarded_port,
System settings:,
|--User ID: 1000,
|--Group ID: 1000,
|--Timezone: america/toronto,
|--IP Status filepath: /tmp/gluetun/ip,
DNS over TLS settings:,
 |--DNS over TLS provider:,
  |--cloudflare,
 |--Caching: enabled,
 |--Block malicious: enabled,
 |--Block surveillance: disabled,
 |--Block ads: disabled,
 |--Allowed hostnames:,
  |--,
 |--Private addresses:,
  |--127.0.0.1/8,
  |--10.0.0.0/8,
  |--172.16.0.0/12,
  |--192.168.0.0/16,
  |--169.254.0.0/16,
  |--::1/128,
  |--fc00::/7,
  |--fe80::/10,
  |--::ffff:0:0/96,
 |--Verbosity level: 1/5,
 |--Verbosity details level: 0/4,
 |--Validation log level: 0/2,
 |--IPv6 resolution: disabled,
 |--Update: every 24h0m0s,
 |--Keep nameserver (disabled blocking): no,
Firewall settings:,
 |--VPN input ports: ,
 |--Input ports: ,
 |--Outbound subnets: 192.168.2.0/24,
HTTP Proxy settings: disabled,
ShadowSocks settings:,
 |--Password: [redacted],
 |--Log: enabled,
 |--Port: 8388,
 |--Method: chacha20-ietf-poly1305,
HTTP Control server:,
 |--Listening port: 8100,
 |--Logging: true,
Public IP check period: 12h0m0s,
Version information: enabled,
Updater: disabled,
,
2020-11-08T13:12:54.718-0400	INFO	storage: Merging by most recent 6556 hardcoded servers and 6556 servers read from /gluetun/servers.json,
2020-11-08T13:12:54.762-0400	INFO	routing: default route found: interface eth0, gateway 172.17.0.1,
2020-11-08T13:12:54.762-0400	INFO	routing: local subnet found: 172.17.0.0/16,
2020-11-08T13:12:54.763-0400	INFO	routing: default route found: interface eth0, gateway 172.17.0.1,
2020-11-08T13:12:54.763-0400	INFO	routing: adding route for 0.0.0.0/0,
2020-11-08T13:12:54.763-0400	INFO	firewall: firewall disabled, only updating allowed subnets internal list,
2020-11-08T13:12:54.764-0400	INFO	routing: default route found: interface eth0, gateway 172.17.0.1,
2020-11-08T13:12:54.764-0400	INFO	routing: adding route for 192.168.2.0/24,
2020-11-08T13:12:54.764-0400	INFO	openvpn configurator: checking for device /dev/net/tun,
2020-11-08T13:12:54.764-0400	WARN	TUN device is not available: open /dev/net/tun: no such file or directory,
2020-11-08T13:12:54.764-0400	INFO	openvpn configurator: creating /dev/net/tun,
2020-11-08T13:12:54.764-0400	INFO	firewall: enabling...,
2020-11-08T13:12:54.883-0400	INFO	firewall: enabled successfully,
2020-11-08T13:12:54.885-0400	INFO	dns over tls: falling back on plaintext DNS at address 1.1.1.1,
2020-11-08T13:12:54.885-0400	INFO	dns configurator: using DNS address 1.1.1.1 internally,
2020-11-08T13:12:54.885-0400	INFO	dns configurator: using DNS address 1.1.1.1 system wide,
2020-11-08T13:12:54.883-0400	INFO	Launching standard output merger,
2020-11-08T13:12:54.888-0400	INFO	http server: listening on 0.0.0.0:8100,
2020-11-08T13:12:54.888-0400	INFO	healthcheck: listening on 127.0.0.1:9999,
2020-11-08T13:12:54.893-0400	INFO	firewall: setting VPN connection through firewall...,
2020-11-08T13:12:54.894-0400	INFO	shadowsocks: listening TCP on 0.0.0.0:8388,
2020-11-08T13:12:54.894-0400	INFO	shadowsocks: listening UDP on 0.0.0.0:8388,
2020-11-08T13:12:54.905-0400	INFO	openvpn configurator: starting openvpn,
2020-11-08T13:12:54.908-0400	INFO	openvpn: OpenVPN 2.4.9 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020,
2020-11-08T13:12:54.908-0400	INFO	openvpn: library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10,
2020-11-08T13:12:54.931-0400	INFO	openvpn: CRL: loaded 1 CRLs from file [[INLINE]],
2020-11-08T13:12:54.932-0400	INFO	openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]172.83.47.250:1197,
2020-11-08T13:12:54.932-0400	INFO	openvpn: UDP link local: (not bound),
2020-11-08T13:12:54.932-0400	INFO	openvpn: UDP link remote: [AF_INET]172.83.47.250:1197,
2020-11-08T13:12:55.362-0400	WARN	openvpn: 'link-mtu' is used inconsistently, local='link-mtu 1570', remote='link-mtu 1542',
2020-11-08T13:12:55.362-0400	WARN	openvpn: 'cipher' is used inconsistently, local='cipher AES-256-CBC', remote='cipher BF-CBC',
2020-11-08T13:12:55.363-0400	WARN	openvpn: 'auth' is used inconsistently, local='auth SHA256', remote='auth SHA1',
2020-11-08T13:12:55.363-0400	WARN	openvpn: 'keysize' is used inconsistently, local='keysize 256', remote='keysize 128',
2020-11-08T13:12:55.363-0400	INFO	openvpn: [toronto405] Peer Connection Initiated with [AF_INET]172.83.47.250:1197,
2020-11-08T13:12:56.589-0400	INFO	openvpn: TUN/TAP device tun0 opened,
2020-11-08T13:12:56.589-0400	INFO	openvpn: /sbin/ip link set dev tun0 up mtu 1500,
2020-11-08T13:12:56.756-0400	INFO	openvpn: /sbin/ip addr add dev tun0 10.51.110.27/24 broadcast 10.51.110.255,
2020-11-08T13:12:56.761-0400	INFO	openvpn: UID set to nonrootuser,
2020-11-08T13:12:56.761-0400	INFO	openvpn: Initialization Sequence Completed,
2020-11-08T13:12:56.761-0400	INFO	dns configurator: downloading root hints from https://raw.githubusercontent.com/qdm12/files/master/named.root.updated,
2020-11-08T13:12:56.761-0400	INFO	VPN routing IP address: 172.83.47.250,
2020-11-08T13:12:56.762-0400	INFO	VPN gateway IP address: 10.51.110.1,
2020-11-08T13:12:56.762-0400	INFO	port forwarding: Found persistent forwarded port data for port 21437,
2020-11-08T13:12:56.762-0400	INFO	port forwarding: Forwarded port data expires in 62 days,
2020-11-08T13:12:56.762-0400	INFO	port forwarding: Port forwarded is 21437 expiring in 62 days,
2020-11-08T13:12:56.894-0400	INFO	port forwarding: Writing port to /tmp/gluetun/forwarded_port,
2020-11-08T13:12:56.895-0400	INFO	firewall: setting allowed input port 21437 through interface tun0...,
2020-11-08T13:12:57.711-0400	INFO	dns configurator: downloading root key from https://raw.githubusercontent.com/qdm12/files/master/root.key.updated,
2020-11-08T13:12:57.979-0400	INFO	dns configurator: generating Unbound configuration,
2020-11-08T13:12:58.293-0400	INFO	dns configurator: 63525 hostnames blocked overall,
2020-11-08T13:12:58.293-0400	INFO	dns configurator: 2698 IP addresses blocked overall,
2020-11-08T13:12:58.576-0400	INFO	dns configurator: starting unbound,
2020-11-08T13:12:58.577-0400	INFO	dns configurator: using DNS address 127.0.0.1 internally,
2020-11-08T13:12:58.577-0400	INFO	dns configurator: using DNS address 127.0.0.1 system wide,
2020-11-08T13:12:58.944-0400	INFO	unbound: init module 0: validator,
2020-11-08T13:12:58.944-0400	INFO	unbound: init module 1: iterator,
2020-11-08T13:12:58.960-0400	INFO	unbound: start of service (unbound 1.10.1).,
2020-11-08T13:12:59.105-0400	INFO	unbound: generate keytag query _ta-4a5c-4f66. NULL IN,
2020-11-08T13:12:59.690-0400	INFO	dns over tls: DNS over TLS is ready,
2020-11-08T13:13:00.383-0400	INFO	There is a new release v3.6.0 (HTTP proxy in Go) created 3 days ago,
2020-11-08T13:13:00.488-0400	INFO	ip getter: Public IP address is 172.83.47.250,
```

**Comment by qdm12** [comment]
Yep it's working, although did you change your gateway/router to something else than 10.0.0.1?

**Comment by Suddow** [comment]
Yup I reconfigured the gateway, it's 192.168.2.1 now

**Comment by qdm12** [comment]
Ah bummer, it turns out there is a workaround. I'll fix it up in case you decide to go back to your `10.0.0.1` router one day 😉 Let's keep the issue opened fot now.

**Comment by qdm12** [comment]
Hey @Suddow when you have the time, can you please try the image with tag `:fix-292`? It should now use the VPN gateway IP address instead of `10.0.0.1` to get your token. I'm no longer subscribed with PIA so I would need you to test it out with port forwarding enabled 😉 I'm half expecting it to not work the first try, meaning we need to use `https://gatewayip:19999` instead of `https://gatewayip:443` but I'm not sure yet. Thanks!!

**Comment by Ca2F** [comment]
I can confirm :fix-292 does not solve the problem:

> Running version fix-292 built on 2020-11-09T01:52:37Z (commit c700154)

📣  Port forwarding is working for PIA v4 servers

🔧  Need help? https://github.com/qdm12/gluetun/issues/new
💻  Email? quentin.mcgaw@gmail.com
☕  Slack? Join from the Slack button on Github
💸  Help me? https://github.com/sponsors/qdm12
2020-11-11T08:37:39.105Z	INFO	OpenVPN version: 2.4.9
2020-11-11T08:37:39.110Z	INFO	Unbound version: 1.10.1
2020-11-11T08:37:39.123Z	INFO	IPtables version: v1.8.4
2020-11-11T08:37:39.123Z	WARN	You are using the old environment variable EXTRA_SUBNETS, please consider changing it to FIREWALL_OUTBOUND_SUBNETS
2020-11-11T08:37:39.123Z	WARN	You are using the old environment variable PROXY, please consider changing it to HTTPPROXY
2020-11-11T08:37:39.123Z	WARN	You are using the old environment variable PROXY_USER, please consider changing it to HTTPPROXY_USER
2020-11-11T08:37:39.123Z	WARN	You are using the old environment variable PROXY_PASSWORD, please consider changing it to HTTPPROXY_PASSWORD
2020-11-11T08:37:39.123Z	INFO	Settings summary below:
OpenVPN settings:
|--User: [redacted]
|--Password: [redacted]
|--Verbosity level: 1
|--Run as root: no
|--Private Internet Access settings:
 |--Network protocol: udp
 |--Regions: sweden
 |--Encryption preset: strong
 |--Port forwarding: on, saved in /port/forwarded_port
System settings:
|--User ID: 1000
|--Group ID: 1000
|--Timezone: 
|--IP Status filepath: /tmp/gluetun/ip
DNS over TLS disabled, using plaintext DNS 1.1.1.1
Firewall settings:
 |--VPN input ports: 
 |--Input ports: 
 |--Outbound subnets: 10.0.0.0/24
HTTP proxy settings:
 |--Port: 8888
 |--Authentication: enabled
 |--Stealth: disabled
 |--Log: disabled
ShadowSocks settings: disabled
HTTP Control server:
 |--Listening port: 8000
 |--Logging: true
Public IP check period: 12h0m0s
Version information: enabled
Updater: disabled

2020-11-11T08:37:39.124Z	INFO	storage: Merging by most recent 6556 hardcoded servers and 0 servers read from /gluetun/servers.json
2020-11-11T08:37:39.182Z	INFO	routing: default route found: interface eth0, gateway 172.17.0.1
2020-11-11T08:37:39.182Z	INFO	routing: local subnet found: 172.17.0.0/16
2020-11-11T08:37:39.182Z	INFO	routing: default route found: interface eth0, gateway 172.17.0.1
2020-11-11T08:37:39.182Z	INFO	routing: adding route for 0.0.0.0/0
2020-11-11T08:37:39.182Z	INFO	firewall: firewall disabled, only updating allowed subnets internal list
2020-11-11T08:37:39.182Z	INFO	routing: default route found: interface eth0, gateway 172.17.0.1
2020-11-11T08:37:39.182Z	INFO	routing: adding route for 10.0.0.0/24
2020-11-11T08:37:39.182Z	INFO	openvpn configurator: checking for device /dev/net/tun
2020-11-11T08:37:39.183Z	INFO	firewall: enabling...
2020-11-11T08:37:39.487Z	INFO	firewall: enabled successfully
2020-11-11T08:37:39.488Z	INFO	Launching standard output merger
2020-11-11T08:37:39.488Z	INFO	dns over tls: using plaintext DNS at address 1.1.1.1
2020-11-11T08:37:39.488Z	INFO	dns configurator: using DNS address 1.1.1.1 internally
2020-11-11T08:37:39.488Z	INFO	dns configurator: using DNS address 1.1.1.1 system wide
2020-11-11T08:37:39.489Z	INFO	http server: listening on 0.0.0.0:8000
2020-11-11T08:37:39.489Z	INFO	healthcheck: listening on 127.0.0.1:9999
2020-11-11T08:37:39.489Z	INFO	http proxy: listening on 0.0.0.0:8888
2020-11-11T08:37:39.489Z	INFO	firewall: setting VPN connection through firewall...
2020-11-11T08:37:39.492Z	INFO	openvpn configurator: starting openvpn
2020-11-11T08:37:39.494Z	INFO	openvpn: OpenVPN 2.4.9 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020
2020-11-11T08:37:39.495Z	INFO	openvpn: library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10
2020-11-11T08:37:39.503Z	INFO	openvpn: CRL: loaded 1 CRLs from file [[INLINE]]
2020-11-11T08:37:39.503Z	INFO	openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]195.246.120.140:1197
2020-11-11T08:37:39.503Z	INFO	openvpn: UDP link local: (not bound)
2020-11-11T08:37:39.503Z	INFO	openvpn: UDP link remote: [AF_INET]195.246.120.140:1197
2020-11-11T08:37:39.680Z	INFO	openvpn: [stockholm404] Peer Connection Initiated with [AF_INET]195.246.120.140:1197
2020-11-11T08:37:40.761Z	INFO	openvpn: OpenVPN ROUTE6: OpenVPN needs a gateway parameter for a --route-ipv6 option and no default was specified by either --route-ipv6-gateway or --ifconfig-ipv6 options
2020-11-11T08:37:40.761Z	INFO	openvpn: OpenVPN ROUTE: failed to parse/resolve route for host/network: 2000::/3
2020-11-11T08:37:40.761Z	INFO	openvpn: TUN/TAP device tun0 opened
2020-11-11T08:37:40.761Z	INFO	openvpn: /sbin/ip link set dev tun0 up mtu 1500
2020-11-11T08:37:40.769Z	INFO	openvpn: /sbin/ip addr add dev tun0 10.30.110.17/24 broadcast 10.30.110.255
2020-11-11T08:37:40.777Z	WARN	openvpn: OpenVPN was configured to add an IPv6 route over tun0. However, no IPv6 has been configured for this interface, therefore the route installation may fail or may not work as expected.
2020-11-11T08:37:40.777Z	INFO	openvpn: UID set to nonrootuser
2020-11-11T08:37:40.777Z	INFO	openvpn: Initialization Sequence Completed
2020-11-11T08:37:40.778Z	INFO	VPN routing IP address: 195.246.120.140
2020-11-11T08:37:40.778Z	INFO	VPN gateway IP address: 10.30.110.1
2020-11-11T08:37:40.778Z	INFO	dns over tls: not restarting because disabled
2020-11-11T08:37:40.802Z	ERROR	port forwarding: cannot obtain token: Get "https://p0227031:***@10.30.110.1/authv3/generateToken": EOF
2020-11-11T08:37:40.802Z	INFO	port forwarding: Trying again in 10s
2020-11-11T08:37:41.096Z	INFO	ip getter: Public IP address is 195.246.120.140
2020-11-11T08:37:41.165Z	INFO	There is a new release v3.7.0 (Privado support and bug fixes) created 30 hours ago
2020-11-11T08:37:50.825Z	ERROR	port forwarding: cannot obtain token: Get "https://redacted-user:***@10.30.110.1/authv3/generateToken": EOF
2020-11-11T08:37:50.825Z	INFO	port forwarding: Trying again in 10s
2020-11-11T08:38:00.850Z	ERROR	port forwarding: cannot obtain token: Get "https://redacted-user:***@10.30.110.1/authv3/generateToken": EOF
2020-11-11T08:38:00.850Z	INFO	port forwarding: Trying again in 10s
2020-11-11T08:38:10.875Z	ERROR	port forwarding: cannot obtain token: Get "https://redacted-user:***@10.30.110.1/authv3/generateToken": EOF
2020-11-11T08:38:10.875Z	INFO	port forwarding: Trying again in 10s
`

**Comment by qdm12** [comment]
Hello @Ca2F thanks for trying it!

I pushed another change with https://github.com/qdm12/gluetun/pull/293/commits/caa8a44f3b93841646c302d5b922344338eb4cc0 can you please try

```sh
docker pull qmcgaw/private-internet-access:fix-292
```

and retry the port forwarding see if it works?

> UPDATE: Semi solved it by setting the EXTRA_SUBNETS=10.0.0.5/30 which is my desktop ip for now.

I'm not sure how `EXTRA_SUBNETS` is relevant at all with the issue though 🤔

**Comment by Ca2F** [comment]
Still not working, but new error: https://pastebin.com/n6d4LYLB

In regards to `EXTRA_SUBNETS`, I've done some testing now. I was under the impression that for me to access the services from other containers that used gluetun for networking i had to declare my local network to be able to access those services locally. This is not the case with the current :latest image. 

With no subnet i can access http resources that uses gluetun for networking and has their ports exposed in the gluetun compose service section. I can also use the proxy functionality from my desktop and port forwarding works like a charm since gluetun can't see my router anymore at 10.0.0.1.

Right now it seems that `EXTRA_SUBNETS` only creates this issue `#292` if you declare most of the possible `10.0.0.X/XX` subnets. 

But @qdm12 Is this the intended behavior for the firewall? When `EXTRA_SUBNETS` was created it probably was to make sure unauthorized local devices could not use the proxy and/or communicate with the clients in the gluetun network.

**Comment by qdm12** [comment]
Thanks for testing and interesting points you made!

I'll ask the PIA engineer again if he knows on what port we should get the token from, as 443 and 19999 don't work it seems.

So to be sure, the 10.0.0.1 port forwarding issue only happens if you have 10.0.0.1 included on your list of EXTRA_SUBNETS right? That might make sense as gluetun isn't aware of 10.0.0.1 by default... except if your Docker network has a 10.0.0.1 then you're screwed 😅 

The origin of EXTRA_SUBNETS was that it was necessary (not firewall but routing wise) in order to allow other hosts to talk to gluetun. I found a way (#268) (thanks to some fellow Redditor) to remove that limitation so now gluetun is accessible for anything going through the Docker gateway, routing wise, as it is for any other containers really. The firewall is another layer on top, for example outbound traffic is restricted and inbound traffic is blocked (except for port forwarding) from the vpn side. And it's also up to the user to setup port forwarding as he wishes with Docker port publishing and his router / host firewall, as for a standard container.

Now I did not know people were using it to reach hosts out of the Docker network from Gluetun so I had to re-add EXTRA_SUBNETS (#194 i think) to support that.

Anyway, long story short, it's more of a routing thing than a security/firewall thing. It's much simpler to specify blocking in the firewall too.

**Comment by Ca2F** [comment]
Thanks for the explanation!

> So to be sure, the 10.0.0.1 port forwarding issue only happens if you have 10.0.0.1 included on your list of EXTRA_SUBNETS right? 

That is correct, in my case this issue is gone when i don't use the `EXTRA_SUBNETS`, which i really don't need.

**Comment by winklevos** [comment]
Yep just noticed this was happening on my container as well! The EXTRA_SUBNETS work around should help

**Comment by qdm12** [comment]
Thanks for letting us know. I need to ping PIA on that. On their repo they use `10.0.0.1` to get the token, hopefully there is another address we can use as it can indeed conflict with a bunch of things.

**Comment by qdm12** [comment]
Hey there, this is about to get fixed since their IP address `10.0.0.1` doesn't work anymore and we are switching to using their new endpoint with `https://privateinternetaccess.com/gtoken/generateToken`, on #423. I'll close this issue once #423 gets closed and merged 😉 

Thanks for your patience!
