### ISSUE TITLE
Error response from daemon ... is restarting, wait until the container is running

### ISSUE THREAD

**Issue by shuntera** [qdm12/gluetun#548]
**Is this urgent?**: No

**Host OS** (approximate answer is fine too): MacOS Catalina 10.5.7

**CPU arch** or **device name**: amd64

**What VPN provider are you using**: Privado

**What are you using to run your container?**: Docker Compose

**What is the version of the program** (See the line at the top of your logs)

Running version latest built on 2021-07-29T01:17:37Z (commit 0bcc6ed)
```

```

**What's the problem** 🤔

Getting an error about the gluetun container is restarting
![vncviewer_pas8W4mymC](https://user-images.githubusercontent.com/11050796/127420103-24ae4b35-7cbc-47cb-b503-a153b306dc5f.png)

**Share your logs... (careful to remove in example tokens)**

```log

2021/07/28 22:01:23 INFO Unbound version: 1.13.1

2021/07/28 22:01:23 INFO IPtables version: v1.8.7

2021/07/28 22:01:23 ERROR cannot read Shadowsocks settings: environment variable SHADOWSOCKS_LISTENING_ADDRESS: missing port in address

2021/07/28 22:01:23 INFO Shutdown successful

========================================

========================================

=============== gluetun ================

========================================

=========== Made with ❤️ by ============

======= https://github.com/qdm12 =======

========================================

========================================


Running version latest built on 2021-07-29T01:17:37Z (commit 0bcc6ed)


🔧 Need help? https://github.com/qdm12/gluetun/discussions/new

🐛 Bug? https://github.com/qdm12/gluetun/issues/new

✨ New feature? https://github.com/qdm12/gluetun/issues/new

☕ Discussion? https://github.com/qdm12/gluetun/discussions/new

💻 Email? quentin.mcgaw@gmail.com

💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12

2021/07/28 22:02:25 INFO Alpine version: 3.14.0

2021/07/28 22:02:25 INFO OpenVPN 2.4 version: 2.4.11

2021/07/28 22:02:25 INFO OpenVPN 2.5 version: 2.5.2

2021/07/28 22:02:25 INFO Unbound version: 1.13.1

2021/07/28 22:02:25 INFO IPtables version: v1.8.7

2021/07/28 22:02:25 ERROR cannot read Shadowsocks settings: environment variable SHADOWSOCKS_LISTENING_ADDRESS: missing port in address

2021/07/28 22:02:25 INFO Shutdown successful

========================================

========================================

=============== gluetun ================

========================================

=========== Made with ❤️ by ============

======= https://github.com/qdm12 =======

========================================

========================================


Running version latest built on 2021-07-29T01:17:37Z (commit 0bcc6ed)


🔧 Need help? https://github.com/qdm12/gluetun/discussions/new

🐛 Bug? https://github.com/qdm12/gluetun/issues/new

✨ New feature? https://github.com/qdm12/gluetun/issues/new

☕ Discussion? https://github.com/qdm12/gluetun/discussions/new

💻 Email? quentin.mcgaw@gmail.com

💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12

2021/07/28 22:03:26 INFO Alpine version: 3.14.0

2021/07/28 22:03:26 INFO OpenVPN 2.4 version: 2.4.11

2021/07/28 22:03:26 INFO OpenVPN 2.5 version: 2.5.2

2021/07/28 22:03:26 INFO Unbound version: 1.13.1

2021/07/28 22:03:26 INFO IPtables version: v1.8.7

2021/07/28 22:03:26 ERROR cannot read Shadowsocks settings: environment variable SHADOWSOCKS_LISTENING_ADDRESS: missing port in address

2021/07/28 22:03:26 INFO Shutdown successful

========================================

========================================

=============== gluetun ================

========================================

=========== Made with ❤️ by ============

======= https://github.com/qdm12 =======

========================================

========================================


Running version latest built on 2021-07-29T01:17:37Z (commit 0bcc6ed)


🔧 Need help? https://github.com/qdm12/gluetun/discussions/new

🐛 Bug? https://github.com/qdm12/gluetun/issues/new

✨ New feature? https://github.com/qdm12/gluetun/issues/new

☕ Discussion? https://github.com/qdm12/gluetun/discussions/new

💻 Email? quentin.mcgaw@gmail.com

💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12

2021/07/28 22:04:28 INFO Alpine version: 3.14.0

2021/07/28 22:04:28 INFO OpenVPN 2.4 version: 2.4.11

2021/07/28 22:04:28 INFO OpenVPN 2.5 version: 2.5.2

2021/07/28 22:04:28 INFO Unbound version: 1.13.1

2021/07/28 22:04:28 INFO IPtables version: v1.8.7

2021/07/28 22:04:28 ERROR cannot read Shadowsocks settings: environment variable SHADOWSOCKS_LISTENING_ADDRESS: missing port in address

2021/07/28 22:04:28 INFO Shutdown successful

========================================

========================================

=============== gluetun ================

========================================

=========== Made with ❤️ by ============

======= https://github.com/qdm12 =======

========================================

========================================


Running version latest built on 2021-07-29T01:17:37Z (commit 0bcc6ed)


🔧 Need help? https://github.com/qdm12/gluetun/discussions/new

🐛 Bug? https://github.com/qdm12/gluetun/issues/new

✨ New feature? https://github.com/qdm12/gluetun/issues/new

☕ Discussion? https://github.com/qdm12/gluetun/discussions/new

💻 Email? quentin.mcgaw@gmail.com

💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12

2021/07/28 22:05:30 INFO Alpine version: 3.14.0

2021/07/28 22:05:30 INFO OpenVPN 2.4 version: 2.4.11

2021/07/28 22:05:30 INFO OpenVPN 2.5 version: 2.5.2

2021/07/28 22:05:30 INFO Unbound version: 1.13.1

2021/07/28 22:05:30 INFO IPtables version: v1.8.7

2021/07/28 22:05:30 ERROR cannot read Shadowsocks settings: environment variable SHADOWSOCKS_LISTENING_ADDRESS: missing port in address

2021/07/28 22:05:30 INFO Shutdown successful

```

**Comment by qdm12** [comment]
Oops indeed. It should be fixed now (wait for it to build https://github.com/qdm12/gluetun/actions/runs/1077056668 and re-pull the image).

It was gluetun erroring when parsing the shadowsocks configuration, since I changed some things a few hours ago.

**Comment by shuntera** [comment]
Not sure if I left it long enough but just tried it again and same error.
Not sure I got a new version when I did a docker pull though, seemed to go
by really fast like it didn’t download a new version.

**Comment by shuntera** [comment]
Same error still showing, here is the log - is that the correct current
build?
The log says I am using SHADOWSOCKS_PORT but that does not appear in my
docker-compose.yml

Stuart




========================================,
========================================,
=============== gluetun ================,
========================================,
=========== Made with ❤️ by ============,
======= https://github.com/qdm12 =======,
========================================,
========================================,
,
Running version latest built on 2021-07-29T02:18:22Z (commit bbe7c5b),
,
🔧 Need help? https://github.com/qdm12/gluetun/discussions/new,
🐛 Bug? https://github.com/qdm12/gluetun/issues/new,
✨ New feature? https://github.com/qdm12/gluetun/issues/new,
☕ Discussion? https://github.com/qdm12/gluetun/discussions/new,
💻 Email? ***@***.***,
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12,
2021/07/29 09:31:43 INFO Alpine version: 3.14.0,
2021/07/29 09:31:43 INFO OpenVPN 2.4 version: 2.4.11,
2021/07/29 09:31:43 INFO OpenVPN 2.5 version: 2.5.2,
2021/07/29 09:31:43 INFO Unbound version: 1.13.1,
2021/07/29 09:31:43 INFO IPtables version: v1.8.7,
2021/07/29 09:31:43 WARN configuration: You are using the old environment
variable SHADOWSOCKS_PORT, please consider using
SHADOWSOCKS_LISTENING_ADDRESS instead,
2021/07/29 09:31:43 ERROR cannot read Shadowsocks settings: environment
variable SHADOWSOCKS_PORT: port is not an integer: ,
2021/07/29 09:31:43 INFO Shutdown successful,
========================================,
========================================,
=============== gluetun ================,
========================================,
=========== Made with ❤️ by ============,
======= https://github.com/qdm12 =======,
========================================,
========================================,
,
Running version latest built on 2021-07-29T02:18:22Z (commit bbe7c5b),
,
🔧 Need help? https://github.com/qdm12/gluetun/discussions/new,
🐛 Bug? https://github.com/qdm12/gluetun/issues/new,
✨ New feature? https://github.com/qdm12/gluetun/issues/new,
☕ Discussion? https://github.com/qdm12/gluetun/discussions/new,
💻 Email? ***@***.***,
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12,
2021/07/29 09:31:58 INFO Alpine version: 3.14.0,
2021/07/29 09:31:58 INFO OpenVPN 2.4 version: 2.4.11,
2021/07/29 09:31:58 INFO OpenVPN 2.5 version: 2.5.2,
2021/07/29 09:31:58 INFO Unbound version: 1.13.1,
2021/07/29 09:31:58 INFO IPtables version: v1.8.7,
2021/07/29 09:31:58 WARN configuration: You are using the old environment
variable SHADOWSOCKS_PORT, please consider using
SHADOWSOCKS_LISTENING_ADDRESS instead,
2021/07/29 09:31:58 ERROR cannot read Shadowsocks settings: environment
variable SHADOWSOCKS_PORT: port is not an integer: ,
2021/07/29 09:31:58 INFO Shutdown successful,
========================================,
========================================,
=============== gluetun ================,
========================================,
=========== Made with ❤️ by ============,
======= https://github.com/qdm12 =======,
========================================,
========================================,
,
Running version latest built on 2021-07-29T02:18:22Z (commit bbe7c5b),
,
🔧 Need help? https://github.com/qdm12/gluetun/discussions/new,
🐛 Bug? https://github.com/qdm12/gluetun/issues/new,
✨ New feature? https://github.com/qdm12/gluetun/issues/new,
☕ Discussion? https://github.com/qdm12/gluetun/discussions/new,
💻 Email? ***@***.***,
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12,
2021/07/29 09:32:25 INFO Alpine version: 3.14.0,
2021/07/29 09:32:25 INFO OpenVPN 2.4 version: 2.4.11,
2021/07/29 09:32:25 INFO OpenVPN 2.5 version: 2.5.2,
2021/07/29 09:32:25 INFO Unbound version: 1.13.1,
2021/07/29 09:32:25 INFO IPtables version: v1.8.7,
2021/07/29 09:32:25 WARN configuration: You are using the old environment
variable SHADOWSOCKS_PORT, please consider using
SHADOWSOCKS_LISTENING_ADDRESS instead,
2021/07/29 09:32:25 ERROR cannot read Shadowsocks settings: environment
variable SHADOWSOCKS_PORT: port is not an integer: ,
2021/07/29 09:32:25 INFO Shutdown successful,
========================================,
========================================,
=============== gluetun ================,
========================================,
=========== Made with ❤️ by ============,
======= https://github.com/qdm12 =======,
========================================,
========================================,
,
Running version latest built on 2021-07-29T02:18:22Z (commit bbe7c5b),
,
🔧 Need help? https://github.com/qdm12/gluetun/discussions/new,
🐛 Bug? https://github.com/qdm12/gluetun/issues/new,
✨ New feature? https://github.com/qdm12/gluetun/issues/new,
☕ Discussion? https://github.com/qdm12/gluetun/discussions/new,
💻 Email? ***@***.***,
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12,
2021/07/29 09:33:18 INFO Alpine version: 3.14.0,
2021/07/29 09:33:18 INFO OpenVPN 2.4 version: 2.4.11,
2021/07/29 09:33:18 INFO OpenVPN 2.5 version: 2.5.2,
2021/07/29 09:33:18 INFO Unbound version: 1.13.1,
2021/07/29 09:33:18 INFO IPtables version: v1.8.7,
2021/07/29 09:33:18 WARN configuration: You are using the old environment
variable SHADOWSOCKS_PORT, please consider using
SHADOWSOCKS_LISTENING_ADDRESS instead,
2021/07/29 09:33:18 ERROR cannot read Shadowsocks settings: environment
variable SHADOWSOCKS_PORT: port is not an integer: ,
2021/07/29 09:33:18 INFO Shutdown successful

**Comment by qdm12** [comment]
It's fixed now sorry, that previous fix didn't fix it 👍

**Comment by shuntera** [comment]
Great, thanks!

Stuart
