### ISSUE TITLE
Bug: Health check failed

### ISSUE THREAD

**Issue by davidakerr** [qdm12/gluetun#845]
### Is this urgent?

Yes and No

### Host OS

Synology (Debian?)

### CPU arch

x86_64

### VPN service provider

Private Internet Access

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2022-02-09T13:49:20.689Z (commit 9596713)

### What's the problem 🤔

I had the container running flawlessly for several days on a Synology NAS deployed with a stack in portainer. It survived a few rebuilds and restarts. Now however I cannot get the container to pass a health check.  I tried pia and nordVPN on multiple regions with similar results. I have also tried a few different gluetun version tags

It does connect _sometimes_ but if restarted or rebuilt can fail for days.

### Share your logs

```log
========================================
========================================
=============== gluetun ================
========================================
=========== Made with ❤️ by ============
======= https://github.com/qdm12 =======
========================================
========================================

Running version latest built on 2022-02-09T13:49:20.689Z (commit 9596713)

🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
🐛 Bug? https://github.com/qdm12/gluetun/issues/new
✨ New feature? https://github.com/qdm12/gluetun/issues/new
☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
💻 Email? quentin.mcgaw@gmail.com
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2022/02/11 21:10:42 WARN You are using the old environment variable VPNSP, please consider changing it to VPN_SERVICE_PROVIDER
2022/02/11 21:10:42 WARN You are using the old environment variable REGION, please consider changing it to SERVER_REGIONS
2022/02/11 21:10:42 INFO routing: default route found: interface eth0, gateway 172.29.0.1
2022/02/11 21:10:42 INFO routing: local ethernet link found: eth0
2022/02/11 21:10:42 INFO routing: local ipnet found: 172.29.0.0/16
2022/02/11 21:10:42 INFO firewall: enabling...
2022/02/11 21:10:42 INFO firewall: enabled successfully
2022/02/11 21:10:42 INFO storage: creating /gluetun/servers.json with 11096 hardcoded servers
2022/02/11 21:10:42 INFO Alpine version: 3.15.0
2022/02/11 21:10:42 INFO OpenVPN 2.4 version: 2.4.11
2022/02/11 21:10:42 INFO OpenVPN 2.5 version: 2.5.4
2022/02/11 21:10:42 INFO Unbound version: 1.13.2
2022/02/11 21:10:42 INFO IPtables version: v1.8.7
2022/02/11 21:10:42 INFO Settings summary:
├── VPN settings:
|   ├── VPN provider settings:
|   |   ├── Name: nordvpn
|   |   └── Server selection settings:
|   |       ├── VPN type: openvpn
|   |       ├── Regions: united kingdom
|   |       └── OpenVPN server selection settings:
|   |           └── Protocol: UDP
|   └── OpenVPN settings:
|       ├── OpenVPN version: 2.5
|       ├── User: [set]
|       ├── Password: [set]
|       ├── Tunnel IPv6: no
|       ├── Network interface: tun0
|       ├── Run OpenVPN as: root
|       └── Verbosity level: 1
├── DNS settings:
|   ├── DNS server address to use: 127.0.0.1
|   ├── Keep existing nameserver(s): no
|   └── DNS over TLS settings:
|       ├── Enabled: yes
|       ├── Update period: every 24h0m0s
|       ├── Unbound settings:
|       |   ├── Authoritative servers:
|       |   |   └── cloudflare
|       |   ├── Caching: yes
|       |   ├── IPv6: no
|       |   ├── Verbosity level: 1
|       |   ├── Verbosity details level: 0
|       |   ├── Validation log level: 0
|       |   ├── System user: root
|       |   └── Allowed networks:
|       |       ├── 0.0.0.0/0
|       |       └── ::/0
|       └── DNS filtering settings:
|           ├── Block malicious: yes
|           ├── Block ads: no
|           ├── Block surveillance: no
|           └── Blocked IP networks:
|               ├── 127.0.0.1/8
|               ├── 10.0.0.0/8
|               ├── 172.16.0.0/12
|               ├── 192.168.0.0/16
|               ├── 169.254.0.0/16
|               ├── ::1/128
|               ├── fc00::/7
|               ├── fe80::/10
|               ├── ::ffff:7f00:1/104
|               ├── ::ffff:a00:0/104
|               ├── ::ffff:a9fe:0/112
|               ├── ::ffff:ac10:0/108
|               └── ::ffff:c0a8:0/112
├── Firewall settings:
|   └── Enabled: yes
├── Log settings:
|   └── Log level: INFO
├── Health settings:
|   ├── Server listening address: 127.0.0.1:9999
|   ├── Address to ping: github.com
|   └── VPN wait durations:
|       ├── Initial duration: 5s
|       └── Additional duration: 5s
├── Shadowsocks server settings:
|   └── Enabled: no
├── HTTP proxy settings:
|   └── Enabled: no
├── Control server settings:
|   ├── Listening address: :8000
|   └── Logging: yes
├── OS Alpine settings:
|   ├── Process UID: 1000
|   └── Process GID: 1000
├── Public IP settings:
|   ├── Fetching: every 12h0m0s
|   └── IP file path: /tmp/gluetun/ip
└── Version settings:
    └── Enabled: yes
2022/02/11 21:10:42 INFO routing: default route found: interface eth0, gateway 172.29.0.1
2022/02/11 21:10:42 INFO routing: adding route for 0.0.0.0/0
2022/02/11 21:10:42 INFO firewall: setting allowed subnets through firewall...
2022/02/11 21:10:42 INFO routing: default route found: interface eth0, gateway 172.29.0.1
2022/02/11 21:10:42 INFO TUN device is not available: open /dev/net/tun: no such file or directory; creating it...
2022/02/11 21:10:42 INFO pprof http server listening on [::]:6060
2022/02/11 21:10:42 INFO dns over tls: using plaintext DNS at address 1.1.1.1
2022/02/11 21:10:42 INFO healthcheck: listening on 127.0.0.1:9999
2022/02/11 21:10:42 INFO http server: listening on :8000
2022/02/11 21:10:42 INFO firewall: setting VPN connection through firewall...
2022/02/11 21:10:42 INFO openvpn: 2022-02-11 21:10:42 WARNING: Compression for receiving enabled. Compression has been used in the past to break encryption. Sent packets are not compressed unless "allow-compression yes" is also set.
2022/02/11 21:10:42 INFO openvpn: OpenVPN 2.5.4 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Nov 15 2021
2022/02/11 21:10:42 INFO openvpn: library versions: OpenSSL 1.1.1l  24 Aug 2021, LZO 2.10
2022/02/11 21:10:42 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]185.44.76.198:1194
2022/02/11 21:10:42 INFO openvpn: UDP link local: (not bound)
2022/02/11 21:10:42 INFO openvpn: UDP link remote: [AF_INET]185.44.76.198:1194
2022/02/11 21:10:47 INFO healthcheck: program has been unhealthy for 5s: restarting VPN
2022/02/11 21:10:47 INFO vpn: stopping
2022/02/11 21:10:47 INFO vpn: starting
```

### Share your configuration

```yml
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8080:8080/tcp
      - 8989:8989/tcp
      - 9117:9117/tcp
      - 7878:7878/tcp
      - 8686:8686/tcp
      - 9696:9696/tcp
    environment:
      - VPNSP=nordvpn
      - OPENVPN_USER=email@me.com
      - OPENVPN_PASSWORD=correctpass
      - REGION=United Kingdom
    logging:
      driver: db
      options: {}
```

**Comment by qdm12** [comment]
It's most likely just outdated server data so gluetun tries to connect to IP addresses no longer valid. Check out the Updating servers data page in the Github wiki, that should fix it for some time. I'll update the hardcoded servers data for nordvpn sometime soon.

**Comment by davidakerr** [comment]
Thanks foor getting back to me, I just got a 30 money back trail with nordvpn to sanity check it wasn't a problem with PIA.

I tried:
`docker run -it --rm -v /volume1/docker/gluetun:/gluetun qmcgaw/gluetun update -enduser -providers pia`

and got

```
2022/02/12 10:24:17 ERROR options validation failed: VPN provider name is not valid: pia at index 0
2022/02/12 10:24:17 INFO Shutdown successful
```

**Comment by davidakerr** [comment]
I did an update of the nordvpn servers as outlined in the WIKI it completed successfully creating a new 2.6mb servers.json file but did not resolve the issue.

**Comment by davidakerr** [comment]
```
version: "3"
services:
  vpn:
    image: azinchen/nordvpn:latest
    network_mode: bridge
    container_name: nordvpnwireguard
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    environment:
      - USER=user
      - PASS=pass
      - COUNTRY=Netherlands
      - GROUP=P2P
      - TECHNOLOGY=openvpn_udp
      - RANDOM_TOP=10
      - RECREATE_VPN_CRON=5 */3 * * *
      - NETWORK=192.168.0.0/24
      - OPENVPN_OPTS=--mute-replay-warnings
```

I'm having some success with this container and settings. I'm not sure why it's working while gluetun is not ?

**Comment by qdm12** [comment]
Can you try with `SERVER_HOSTNAMER=nl-ch9.nordvpn.com`?

**Comment by davidakerr** [comment]
Same behaviour with that env variable, unhealthy for periods of hours to days then seemingly randomly connects and stays connected for an indeterminate amount of time hours to days then fails on loop. Other openVPN containers behave similarly on my NAS. I've read reports it happens to other people too.

https://www.blackvoid.club/qbittorrent-via-vpn-docker-container-running-on-synology-nas/ 

After visiting here I found the one configuration that seems to work (at the bottom of that page)

That link has warning such as :

> UPDATE: added warnings for running these examples under DSM 7! Changes to the privileged:true and the need for cap_add and devices parameters

> NOTE: With the new DSM 7 most containers that run in privileged mode will not work. Because of that, I have added a few images on the bottom that runs fine in DSM 7 so consider running them. Those images are a combination of two containers (VPN and client) that run as a single stack.

**Comment by qdm12** [comment]
Try with `FIREWALL=off`? As in maybe it's Synology firewall misbehaving for some reason...
Also are you sure the firewall allows the gluetun container to connect to vpn servers?

**Comment by RomeoNotaLoka** [comment]
I had a similar problem in portainer. After rebooting my server everything started working again.

**Comment by qdm12** [comment]
@RomeoNotaLoka actually since you got it working, would you mind please help answering at #873 that way I can also improve the nordvpn wiki page. Thanks!

**Comment by davidakerr** [comment]
I think it's likely the firewall. I haven't had a chance to verify.
